export const levels = [
  { id: 1, title: 'AI Foundations', description: 'Build your mental model of AI.', unlocked: true },
  { id: 2, title: 'LLM Fundamentals', description: 'Tokens, embeddings, attention & prediction.', unlocked: false },
  { id: 3, title: 'Prompt Engineering', description: 'Learn to communicate with models effectively.', unlocked: false },
  { id: 4, title: 'LLM Applications', description: 'Learn API basics and build with language models.', unlocked: false },
  { id: 5, title: 'RAG', description: 'Connect models to your own knowledge.', unlocked: false },
  { id: 6, title: 'Agents', description: 'Models that reason and use tools.', unlocked: false },
  { id: 7, title: 'MCP', description: 'A standard way to connect AI to tools and data.', unlocked: false },
  { id: 8, title: 'Orchestration', description: 'Design reliable multi-step AI systems.', unlocked: false }
];

export const foundationLessons = [
  { id: 'ai', title: 'What is Artificial Intelligence?', description: 'Understand what AI means and how it differs from ordinary software.', difficulty: 'Beginner', xp: 25, visual: ['Rules', 'Data', 'AI System', 'Output'], content: '<p>Artificial Intelligence is a broad field focused on building systems that can perform tasks that normally require human-like intelligence.</p><p>The useful mental model: software follows instructions; AI systems can learn patterns from examples and use those patterns to produce useful outputs.</p>', quiz: { question: 'Which best describes AI?', options: ['A programming language', 'Systems that perform tasks requiring intelligence', 'A database', 'A web framework'], answer: 1 } },
  { id: 'genai', title: 'What is Generative AI?', description: 'See how AI systems can create new text, images, code and more.', difficulty: 'Beginner', xp: 25, visual: ['Prompt', 'Model', 'Generated Output'], content: '<p>Generative AI refers to models that generate new content from learned patterns. Text, images, audio and code can all be generated.</p><p>Large language models are one important category of generative AI, focused on language.</p>', quiz: { question: 'What is a defining capability of generative AI?', options: ['Only storing data', 'Generating new content', 'Only sorting records', 'Only rendering websites'], answer: 1 } },
  { id: 'llm', title: 'What is an LLM?', description: 'Learn the basic idea behind large language models without the math.', difficulty: 'Beginner', xp: 25, visual: ['Text', 'Tokens', 'LLM', 'Next token'], content: '<p>A Large Language Model (LLM) is a model trained on large amounts of text to learn patterns in language. At its core, a text-generation LLM repeatedly predicts what token should come next.</p>', quiz: { question: 'What does a text-generation LLM fundamentally predict?', options: ['The next token', 'A database row', 'A CSS property', 'A network packet'], answer: 0 } },
  { id: 'apps', title: 'How LLM applications work', description: 'Build a simple mental model of the pieces around an LLM.', difficulty: 'Beginner', xp: 25, visual: ['User', 'App', 'LLM', 'Response'], content: '<p>An LLM application usually has more than the model. A user interacts with an application, the application prepares a request, the LLM generates a response, and the application presents it.</p>', quiz: { question: 'What usually sits between a user and an LLM in an application?', options: ['An application layer', 'A compiler only', 'A spreadsheet', 'A router only'], answer: 0 } },
  { id: 'usecases', title: 'Real-world LLM use cases', description: 'Explore practical ways language models are used today.', difficulty: 'Beginner', xp: 25, visual: ['LLM', 'Chat', 'Code', 'Search', 'Summarize'], content: '<p>LLMs can power chat assistants, summarization, code assistance, classification, extraction, content drafting and question-answering.</p>', quiz: { question: 'Which is a realistic LLM use case?', options: ['Summarizing a document', 'Replacing electricity', 'Increasing screen resolution', 'Formatting a hard drive'], answer: 0 } }
];

export const llmLessons = [
  { id: 'llm-01', title: 'What is an LLM?', description: 'Build the simplest useful mental model of a Large Language Model.', difficulty: 'Beginner', xp: 20, objective: 'Understand what an LLM is and what a text-generation model does.', type: 'llm-intro', content: '<p><strong>LLM</strong> stands for <strong>Large Language Model</strong>. It learns patterns from language data and can generate useful continuations.</p>', visual: ['User', 'Prompt', 'LLM', 'Generated text'], quiz: { question: 'Which one best describes an LLM?', options: ['A database containing every answer', 'A model trained to learn patterns from large amounts of data and generate text', 'A search engine', 'A normal if/else program'], answer: 1 } },
  { id: 'llm-02', title: 'Why Do LLMs Matter?', description: 'Recognize where language models can be useful in real products.', difficulty: 'Beginner', xp: 20, objective: 'Connect common tasks with practical LLM use cases.', type: 'use-case-match', content: '<p>LLMs can support many language tasks through different instructions and application experiences. The surrounding application still matters.</p>', visual: ['Chat', 'Summarize', 'Translate', 'Code', 'Tutor'], matches: [['Customer support assistant', 'Chatbot'], ['Turn a long article into 5 bullets', 'Summarization'], ['Convert a paragraph from Hindi to English', 'Translation'], ['Generate a Python function', 'Code generation'], ['Explain photosynthesis to a student', 'Tutoring']], quiz: { question: 'Which task is a good fit for an LLM?', options: ['Summarizing a document', 'Increasing monitor brightness', 'Replacing a hard drive', 'Measuring room temperature without a sensor'], answer: 0 } },
  { id: 'llm-03', title: 'Meet the Tokens', description: 'See how text can be broken into smaller pieces before a model processes it.', difficulty: 'Beginner', xp: 30, objective: 'Understand tokens and why tokenization is a preprocessing step.', type: 'tokenizer', content: '<p>Before an LLM processes text, text is represented as <strong>tokens</strong>. A token can be a word, part of a word, punctuation, or another piece depending on the tokenizer.</p><p>This is an educational simulation; real tokenizers can split text differently.</p>', visual: ['Text', 'Token', 'Token', 'Token', '...'], quiz: { question: 'Why does an LLM tokenize text?', options: ['To make text easier for the model to process', 'To translate text into English', 'To store text in a database', 'To search Google'], answer: 0 } },
  { id: 'llm-04', title: 'From Tokens to Numbers', description: 'Build intuition for embeddings and vector representations.', difficulty: 'Beginner', xp: 30, objective: 'Understand that tokens can be represented as numerical vectors.', type: 'embeddings', content: '<p>An <strong>embedding</strong> is a vector representation of information. The numbers below are illustrative, not a real embedding.</p>', visual: ['cheese', '→', '[ 0.12, -0.55, 1.03, ... ]'], quiz: { question: 'What is an embedding?', options: ['A vector representation of information', 'A database', 'A prompt template', 'A generated answer'], answer: 0 } },
  { id: 'llm-05', title: 'Attention: What Should the Model Focus On?', description: 'Explore how attention helps relate different tokens in a sequence.', difficulty: 'Beginner', xp: 35, objective: 'Understand attention as a way to assign different importance to token relationships.', type: 'attention', content: '<p><strong>Attention</strong> helps a transformer assign different importance to relationships between tokens while processing a sequence.</p>', visual: ['Most', 'famous', 'cheese', 'in', 'France', '?'], quiz: { question: 'Which word is especially useful when answering “Most famous cheese in France?”', options: ['cheese', 'banana', 'car', 'pencil'], answer: 0 } },
  { id: 'llm-06', title: 'How an LLM Generates Text', description: 'Watch a simplified next-token prediction loop build a response.', difficulty: 'Beginner', xp: 35, objective: 'Understand generation as repeated next-token prediction.', type: 'generation', content: '<p>A text-generation LLM predicts a possible next token from context, adds it to the context, and predicts again.</p><p>The probabilities in this simulation are illustrative and are not real model inference.</p>', visual: ['Input', 'Tokenization', 'Representations', 'Transformer', 'Next token', 'Output'], generation: { prompt: 'The sky is', steps: [{ token: 'blue', probability: 70, alternatives: [['green', 15], ['clear', 8], ['bright', 4]] }, { token: 'and', probability: 52, alternatives: [['very', 20], ['so', 12], ['today', 6]] }, { token: 'clear', probability: 61, alternatives: [['bright', 16], ['wide', 9], ['calm', 5]] }, { token: 'today', probability: 58, alternatives: [['outside', 17], ['above', 11], ['here', 6]] }] }, quiz: { question: 'What is the core idea behind text generation in an LLM?', options: ['Repeatedly predicting the next token from context', 'Looking up every sentence in a database', 'Choosing a random paragraph once', 'Rendering the answer with CSS'], answer: 0 } },
  { id: 'llm-07', title: 'What Are Parameters?', description: 'Understand parameters as learned numerical values inside a model.', difficulty: 'Beginner', xp: 25, objective: 'Understand what parameters are and why model size matters.', type: 'parameters', content: '<p><strong>Parameters</strong> are learned numerical values inside a model. More parameters do not automatically mean better overall performance.</p>', visual: ['weight', 'weight', 'weight', 'weight', '...'], quiz: { question: 'What is a parameter?', options: ['A learned numerical value in a model', 'A user question', 'A database record', 'A browser setting'], answer: 0 } },
  { id: 'llm-08', title: 'Temperature, Top-k & Top-p', description: 'Experiment with the main generation controls conceptually.', difficulty: 'Beginner', xp: 40, objective: 'Understand how temperature, top-k and top-p influence candidate selection.', type: 'sampling', content: '<p><strong>Temperature</strong> changes how concentrated or spread out candidate probabilities are. <strong>Top-k</strong> limits candidates to k choices. <strong>Top-p</strong> keeps a candidate set until a cumulative probability threshold is reached.</p><p>This is a conceptual simulation, not real inference.</p>', visual: ['Candidates', 'Temperature', 'Top-k', 'Top-p'], sampling: { candidates: [['robot', 0.42], ['lab', 0.25], ['house', 0.16], ['garden', 0.09], ['station', 0.05], ['forest', 0.03]] }, quiz: { question: 'What does a higher temperature generally encourage?', options: ['More varied candidate selection', 'A guaranteed correct answer', 'Fewer tokens in the prompt', 'A larger model'], answer: 0 } }
];

const promptVisual = (steps) => steps;
const pair = (weak, strong) => ({ weak, strong });

export const promptLessons = [
  { id: 'prompt-01', title: 'What Makes a Good Prompt?', description: 'Learn why clarity and useful specificity beat vague instructions.', difficulty: 'Beginner', xp: 20, objective: 'Recognize the stronger prompt and explain why it provides more useful guidance.', type: 'prompt-compare', content: '<p>Prompting is about giving an LLM useful instructions and context. A better prompt is not necessarily a longer prompt.</p><p><strong>Useful specificity</strong> means including information that helps the model understand the task, audience, constraints, or desired result.</p>', visual: promptVisual(['Vague request', 'Identify missing guidance', 'Add useful detail', 'Clearer prompt']), pairs: [pair('Tell me about AI.', 'Explain Generative AI to a beginner in 5 bullet points using simple language and one real-world example.'), pair('Write code.', 'Write a JavaScript function that reverses a string. Include a short explanation and one example.'), pair('Tell me about India.', 'Act as a travel guide and suggest 3 places in India for a solo traveler visiting for 2 days.')], quiz: { question: 'Which principle is best?', options: ['Longer prompts are always better', 'Useful specificity is more important than unnecessary length', 'Prompts should never include context', 'A role guarantees expertise'], answer: 1 } },
  { id: 'prompt-02', title: 'Prompt Anatomy', description: 'Build a prompt from System, Instruction and Input / Examples.', difficulty: 'Beginner', xp: 30, objective: 'Identify the job of each core prompt component.', type: 'prompt-anatomy', content: '<p>A useful foundation is <strong>System + Instruction + Input / Examples</strong>.</p><p>System gives behavioral or contextual guidance. Instruction says what to do. Input or examples provide the task data or demonstrate a pattern.</p>', visual: promptVisual(['SYSTEM', 'INSTRUCTION', 'INPUT / EXAMPLES']), anatomy: [{ label: 'SYSTEM', text: 'You are a helpful career coach.', answer: 'system' }, { label: 'INSTRUCTION', text: 'Create a professional LinkedIn bio.', answer: 'instruction' }, { label: 'INPUT', text: 'Name: Alex · Role: Backend Developer · Experience: 3 years', answer: 'input' }], quiz: { question: 'Which component mainly describes who or how the assistant should behave?', options: ['System', 'Instruction', 'Input'], answer: 0 } },
  { id: 'prompt-03', title: 'Be Specific', description: 'Turn an ambiguous request into a useful, task-ready prompt.', difficulty: 'Beginner', xp: 30, objective: 'Select relevant details that reduce ambiguity.', type: 'specificity-builder', content: '<p>Start with <strong>“Explain databases.”</strong> Then add only details that are useful for the intended outcome.</p><p>Topic, audience, length, tone, format and goal can make the request easier to interpret.</p>', visual: promptVisual(['Topic', 'Audience', 'Length', 'Tone', 'Format', 'Goal']), fields: [{ id: 'topic', label: 'Topic', options: ['Databases', 'Weather', 'Football'], answer: 'Databases' }, { id: 'audience', label: 'Audience', options: ['Beginner developers', 'Database administrators', 'Random audience'], answer: 'Beginner developers' }, { id: 'length', label: 'Length', options: ['500 words', '50 pages', 'Any length'], answer: '500 words' }, { id: 'tone', label: 'Tone', options: ['Friendly', 'Aggressive', 'Unspecified'], answer: 'Friendly' }, { id: 'format', label: 'Format', options: ['Headings + examples', 'Anything', 'No structure'], answer: 'Headings + examples' }, { id: 'goal', label: 'Goal', options: ['Help a beginner understand the basics', 'Use as much jargon as possible', 'Avoid explaining anything'], answer: 'Help a beginner understand the basics' }], quiz: { question: 'What makes a prompt more useful?', options: ['Adding relevant details about the desired outcome', 'Adding random words', 'Making it as long as possible', 'Removing the audience'], answer: 0 } },
  { id: 'prompt-04', title: 'Give the AI a Role', description: 'Use roles to provide perspective, context and communication guidance.', difficulty: 'Beginner', xp: 25, objective: 'Choose when a role provides useful context without assuming magical expertise.', type: 'role-match', content: '<p>A role can establish a desired <strong>perspective, context, expertise framing, or communication style</strong>.</p><p>It does not magically give a model new capabilities or guarantee expertise.</p>', visual: promptVisual(['Task', 'Role context', 'Desired response style']), roles: ['Software Engineer', 'Teacher', 'Travel Agent', 'Chef'], task: 'Explain recursion to a beginner.', answer: 'Teacher', example: 'You are a teacher. Explain recursion to a beginner using a simple analogy and one short code example.', quiz: { question: 'What is a useful way to think about role prompting?', options: ['It provides behavioral or contextual guidance', 'It guarantees expert-level correctness', 'It adds new model parameters', 'It replaces the task instruction'], answer: 0 } },
  { id: 'prompt-05', title: 'Examples Change Everything', description: 'Compare zero-shot and few-shot prompting through classification.', difficulty: 'Beginner', xp: 35, objective: 'Understand how examples can demonstrate a task pattern and output format.', type: 'few-shot', content: '<p><strong>Zero-shot</strong> asks the model to perform a task without examples. <strong>Few-shot</strong> provides a small number of examples.</p><p>Examples can help demonstrate the desired task, pattern, and output format. They do not guarantee correctness.</p>', visual: promptVisual(['Task', 'Examples', 'Pattern', 'Output']), examples: [['I absolutely loved this movie.', 'Positive'], ['This was a terrible experience.', 'Negative']], tests: ['The product works perfectly.', 'Pretty useful overall'], labels: ['Positive', 'Negative'], quiz: { question: 'Why can few-shot examples be useful?', options: ['They demonstrate a desired pattern or format', 'They guarantee accuracy', 'They permanently retrain the model', 'They remove the need for a task'], answer: 0 } },
  { id: 'prompt-06', title: 'Control the Output', description: 'Choose an output format that makes the result useful for the task.', difficulty: 'Beginner', xp: 35, objective: 'Match tasks with appropriate output structures and understand validation needs.', type: 'output-format', content: '<p>You can ask for <strong>JSON, tables, bullets, or formatted text</strong> when a particular structure makes the output easier to use.</p><p>Requesting JSON does not guarantee valid JSON in every model or system. Applications should still validate structured output.</p>', visual: promptVisual(['Task', 'Format instruction', 'Structured result']), formats: [{ id: 'free', label: 'Free text', best: false }, { id: 'json', label: 'JSON', best: true }, { id: 'table', label: 'Table', best: false }, { id: 'bullets', label: 'Bullet list', best: false }], json: '{\n  "name": "John",\n  "company": "Acme",\n  "year": 2024,\n  "role": "Backend Developer"\n}', quiz: { question: 'What should an application do with model-generated JSON?', options: ['Validate it before relying on the structure', 'Assume it is always valid', 'Convert it to a password', 'Remove all field names'], answer: 0 } },
  { id: 'prompt-07', title: 'Give Context & Constraints', description: 'Decompose a realistic prompt into role, task, context, constraints and output.', difficulty: 'Beginner', xp: 35, objective: 'Identify the information that makes a prompt actionable and appropriately bounded.', type: 'prompt-decompose', content: '<p>Compare: <em>“Write an email.”</em> with a prompt that includes role, task, context, constraints and output.</p><p>The goal is not to add every possible field. Add the information that is relevant to the task.</p>', visual: promptVisual(['ROLE', 'TASK', 'CONTEXT', 'CONSTRAINTS', 'OUTPUT']), prompt: { role: 'You are a project manager.', task: 'Write a concise professional email to a software client.', context: 'The delivery date moved from Friday to Monday because integration testing found unexpected issues.', constraints: 'Keep the tone transparent and reassuring. Do not blame the client.', output: 'A concise professional email.' }, quiz: { question: 'Which detail is a constraint?', options: ['Do not blame the client', 'The client exists', 'Write an email', 'Project manager'], answer: 0 } },
  { id: 'prompt-08', title: 'Prompt Refinement Lab', description: 'Repair a vague resume request step by step and track guidance coverage.', difficulty: 'Intermediate', xp: 50, objective: 'Progressively add relevant task, context, audience, constraints and format information.', type: 'refinement', content: '<p>Start with <strong>“Make me a resume.”</strong> Your job is to refine it, not to make it artificially long.</p><p>The meter below is <strong>prompt completeness / guidance coverage</strong>, not a scientific quality score.</p>', visual: promptVisual(['Weak prompt', 'Add target', 'Add context', 'Add constraints', 'Review']), refinement: [{ text: 'Make me a resume.', coverage: ['task'] }, { text: 'Create a resume for a software developer.', coverage: ['task', 'audience'] }, { text: 'Create a resume for a junior full-stack developer.', coverage: ['task', 'audience', 'context'] }, { text: 'Create a one-page resume for a junior full-stack developer with 1 year of experience.', coverage: ['task', 'audience', 'context', 'format'] }, { text: 'Create a one-page ATS-friendly resume for a junior full-stack developer with 1 year of experience. Emphasize React, Node.js and MongoDB. Use concise bullet points.', coverage: ['task', 'audience', 'context', 'constraints', 'format'] }], quiz: { question: 'What should guide refinement?', options: ['Relevant missing information', 'Maximum possible words', 'Random technical jargon', 'Repeating the same sentence'], answer: 0 } },
  { id: 'prompt-09', title: 'Prompt Engineering Challenge', description: 'Repair weak prompts for study plans, summaries, code, classification, interviews and email rewriting.', difficulty: 'Challenge', xp: 75, objective: 'Construct prompts by selecting components that fit each task.', type: 'prompt-challenge', content: '<p>Each scenario starts weak. Select the useful building blocks instead of optimizing for word count.</p><p>Different tasks need different components: a study plan may need goal and constraints; classification may benefit from examples and output format.</p>', visual: promptVisual(['Weak prompt', 'Choose components', 'Check requirements', 'Better prompt']), scenarios: [
    { task: 'Generate a study plan.', requiredComponents: ['goal', 'context', 'constraints', 'output'], components: ['role', 'goal', 'context', 'input', 'constraints', 'output', 'examples'] },
    { task: 'Summarize a document.', requiredComponents: ['goal', 'input', 'constraints', 'output'], components: ['role', 'goal', 'context', 'input', 'constraints', 'output', 'examples'] },
    { task: 'Generate code.', requiredComponents: ['goal', 'context', 'constraints', 'output'], components: ['role', 'goal', 'context', 'input', 'constraints', 'output', 'examples'] },
    { task: 'Classify customer feedback.', requiredComponents: ['goal', 'input', 'output', 'examples'], components: ['role', 'goal', 'context', 'input', 'constraints', 'output', 'examples'] },
    { task: 'Create an interview simulation.', requiredComponents: ['role', 'goal', 'context', 'constraints', 'output'], components: ['role', 'goal', 'context', 'input', 'constraints', 'output', 'examples'] },
    { task: 'Rewrite an email.', requiredComponents: ['goal', 'input', 'constraints', 'output'], components: ['role', 'goal', 'context', 'input', 'constraints', 'output', 'examples'] }
  ], quiz: { question: 'How should these challenges be evaluated?', options: ['By whether relevant required components are present', 'By character count only', 'By punctuation count', 'By making every prompt identical'], answer: 0 } },
  { id: 'prompt-10', title: 'PROMPT ENGINEER — FINAL BOSS', description: 'Construct a production-minded prompt for an AI study assistant.', difficulty: 'Final Boss', xp: 150, objective: 'Build a prompt that covers role, objective, learner context, constraints, output and useful examples.', type: 'prompt-final', content: '<p>You are building an <strong>AI study assistant</strong>. Construct instructions that tell an LLM how to teach a beginner without overwhelming them.</p><p>Choose the components that matter, review the assembled prompt, then submit it. Passing requires <strong>70%</strong> coverage.</p>', visual: promptVisual(['Role', 'Objective', 'Learner context', 'Constraints', 'Output', 'Examples']), finalComponents: [
    { id: 'role', label: 'ROLE', text: 'Act as a patient study mentor.' },
    { id: 'goal', label: 'OBJECTIVE', text: 'Teach the learner one concept at a time using simple explanations.' },
    { id: 'context', label: 'LEARNER CONTEXT', text: 'The learner is a beginner and may need unfamiliar terms explained.' },
    { id: 'constraints', label: 'CONSTRAINTS', text: 'Use examples, avoid overwhelming the learner, and adapt based on the learner’s answer.' },
    { id: 'output', label: 'OUTPUT', text: 'Return structured lesson sections and ask one short question after each concept.' },
    { id: 'examples', label: 'EXAMPLE', text: 'Example lesson flow: Concept → Simple explanation → Example → Check question.' }
  ], requiredComponents: ['role', 'goal', 'context', 'constraints', 'output'], quiz: null }
];

export const finalChallenge = {
  id: 'llm-final', title: 'LLM Fundamentals — Final Challenge', description: 'Prove that you can trace a prompt through the core LLM concepts.', difficulty: 'Challenge', xp: 100, objective: 'Pass with at least 70% by applying the concepts from Missions 01–08.', type: 'final', questions: [
    { question: 'What does LLM stand for?', options: ['Large Language Model', 'Learning Logic Machine', 'Language Lookup Memory', 'Large Logic Module'], answer: 0 },
    { question: 'What is a token?', options: ['A piece of text used in processing', 'A database table', 'A model parameter', 'A browser cookie'], answer: 0 },
    { question: 'What is an embedding?', options: ['A vector representation of information', 'A final generated answer', 'A prompt template', 'A search engine'], answer: 0 },
    { question: 'What does attention help a transformer do?', options: ['Relate tokens with different importance in context', 'Search the internet', 'Store every answer', 'Increase screen resolution'], answer: 0 },
    { question: 'Put this simplified generation pipeline in order.', order: ['Input text', 'Tokenization', 'Transformer / attention', 'Next-token prediction', 'Output'], type: 'order' },
    { question: 'Which statement about parameters is correct?', options: ['They are learned numerical values inside a model', 'They are user questions', 'They are database records', 'They are browser settings'], answer: 0 },
    { question: 'What does lower temperature generally do?', options: ['Makes the distribution more concentrated and selection more predictable', 'Adds parameters', 'Removes tokenization', 'Turns the model into a search engine'], answer: 0 },
    { question: 'What does top-k do?', options: ['Limits candidates to the k most probable choices', 'Chooses every candidate', 'Changes model size', 'Converts tokens into English'], answer: 0 },
    { question: 'What does top-p do?', options: ['Chooses the smallest candidate group reaching a probability threshold', 'Always chooses exactly three tokens', 'Changes the number of model parameters', 'Disables attention'], answer: 0 },
    { question: 'In one short sentence, explain what an LLM does when it generates text.', type: 'short', answer: 'predict' }
  ]
};

export const achievements = [
  { id: 'first-step', icon: '↗', title: 'FIRST STEP', description: 'Complete your first lesson.' },
  { id: 'curious-mind', icon: '✦', title: 'CURIOUS MIND', description: 'Complete 3 lessons.' },
  { id: 'ai-explorer', icon: '◆', title: 'AI EXPLORER', description: 'Complete Level 1.' },
  { id: 'token-tamer', icon: '▦', title: 'TOKEN TAMER', description: 'Complete the tokenization mission.' },
  { id: 'attention-seeker', icon: '...', title: 'ATTENTION SEEKER', description: 'Complete the attention mission.' },
  { id: 'model-thinker', icon: '◇', title: 'MODEL THINKER', description: 'Complete the parameters mission.' },
  { id: 'llm-initiate', icon: '◎', title: 'LLM INITIATE', description: 'Complete LLM Fundamentals.' },
  { id: 'prompt-apprentice', icon: '✎', title: 'PROMPT APPRENTICE', description: 'Complete 3 Prompt Engineering missions.' },
  { id: 'context-master', icon: '⌁', title: 'CONTEXT MASTER', description: 'Complete Context & Constraints.' },
  { id: 'example-builder', icon: '▤', title: 'EXAMPLE BUILDER', description: 'Complete the Few-Shot mission.' },
  { id: 'prompt-refiner', icon: '↻', title: 'PROMPT REFINER', description: 'Complete the Prompt Refinement Lab.' },
  { id: 'prompt-engineer', icon: '★', title: 'PROMPT ENGINEER', description: 'Complete the entire Prompt Engineering level.' }
];

export const lessons = [...foundationLessons, ...llmLessons, ...promptLessons, finalChallenge];
