export const levels = [
  { id: 1, title: 'AI Foundations', description: 'Build your mental model of AI.', unlocked: true },
  { id: 2, title: 'LLM Fundamentals', description: 'Tokens, embeddings, attention & prediction.', unlocked: false },
  { id: 3, title: 'Prompt Engineering', description: 'Learn to communicate with models effectively.', unlocked: false },
  { id: 4, title: 'Open Source AI', description: 'Hugging Face, Ollama and local models.', unlocked: false },
  { id: 5, title: 'RAG', description: 'Connect models to your own knowledge.', unlocked: false },
  { id: 6, title: 'Agents', description: 'Models that reason and use tools.', unlocked: false },
  { id: 7, title: 'MCP', description: 'A standard way to connect AI to tools and data.', unlocked: false },
  { id: 8, title: 'Agent Orchestration', description: 'Design reliable multi-step AI systems.', unlocked: false }
];

export const foundationLessons = [
  { id: 'ai', title: 'What is Artificial Intelligence?', description: 'Understand what AI means and how it differs from ordinary software.', difficulty: 'Beginner', xp: 25, visual: ['Rules', 'Data', 'AI System', 'Output'], content: '<p>Artificial Intelligence is a broad field focused on building systems that can perform tasks that normally require human-like intelligence.</p><p>The useful mental model: software follows instructions; AI systems can learn patterns from examples and use those patterns to produce useful outputs.</p>', quiz: { question: 'Which best describes AI?', options: ['A programming language', 'Systems that perform tasks requiring intelligence', 'A database', 'A web framework'], answer: 1 } },
  { id: 'genai', title: 'What is Generative AI?', description: 'See how AI systems can create new text, images, code and more.', difficulty: 'Beginner', xp: 25, visual: ['Prompt', 'Model', 'Generated Output'], content: '<p>Generative AI refers to models that generate new content from learned patterns. Text, images, audio and code can all be generated.</p><p>Large language models are one important category of generative AI, focused on language.</p>', quiz: { question: 'What is a defining capability of generative AI?', options: ['Only storing data', 'Generating new content', 'Only sorting records', 'Only rendering websites'], answer: 1 } },
  { id: 'llm', title: 'What is an LLM?', description: 'Learn the basic idea behind large language models without the math.', difficulty: 'Beginner', xp: 25, visual: ['Text', 'Tokens', 'LLM', 'Next token'], content: '<p>A Large Language Model (LLM) is a model trained on large amounts of text to learn patterns in language. At its core, a text-generation LLM repeatedly predicts what token should come next.</p><p>You do not need transformer math yet. First, remember the pipeline: text becomes tokens, the model processes those tokens, and it predicts a continuation.</p>', quiz: { question: 'What does a text-generation LLM fundamentally predict?', options: ['The next token', 'A database row', 'A CSS property', 'A network packet'], answer: 0 } },
  { id: 'apps', title: 'How LLM applications work', description: 'Build a simple mental model of the pieces around an LLM.', difficulty: 'Beginner', xp: 25, visual: ['User', 'App', 'LLM', 'Response'], content: '<p>An LLM application usually has more than the model. A user interacts with an application, the application prepares a request, the LLM generates a response, and the application presents it.</p><p>Later, you will add APIs, retrieval, tools and memory to this mental model.</p>', quiz: { question: 'What usually sits between a user and an LLM in an application?', options: ['An application layer', 'A compiler only', 'A spreadsheet', 'A router only'], answer: 0 } },
  { id: 'usecases', title: 'Real-world LLM use cases', description: 'Explore practical ways language models are used today.', difficulty: 'Beginner', xp: 25, visual: ['LLM', 'Chat', 'Code', 'Search', 'Summarize'], content: '<p>LLMs can power chat assistants, summarization, code assistance, classification, extraction, content drafting and question-answering.</p><p>The important engineering lesson is that the model is a component. Good products combine the model with the right data, instructions, interface and constraints.</p>', quiz: { question: 'Which is a realistic LLM use case?', options: ['Summarizing a document', 'Replacing electricity', 'Increasing screen resolution', 'Formatting a hard drive'], answer: 0 } }
];

export const llmLessons = [
  { id: 'llm-01', title: 'What is an LLM?', description: 'Build the simplest useful mental model of a Large Language Model.', difficulty: 'Beginner', xp: 20, objective: 'Understand what an LLM is and what a text-generation model does.', type: 'llm-intro', content: '<p><strong>LLM</strong> stands for <strong>Large Language Model</strong>. It is a model trained on large amounts of language data to learn patterns in text and generate useful continuations.</p><p>A helpful beginner analogy is an <strong>advanced autocomplete system</strong>. Unlike a simple autocomplete, an LLM can use much more context to generate conversations, explanations, summaries, code and other text.</p><p>It is not a database containing every answer. It generates output from learned patterns.</p>', visual: ['User', 'Prompt', 'LLM', 'Generated text'], quiz: { question: 'Which one best describes an LLM?', options: ['A database containing every answer', 'A model trained to learn patterns from large amounts of data and generate text', 'A search engine', 'A normal if/else program'], answer: 1 } },
  { id: 'llm-02', title: 'Why Do LLMs Matter?', description: 'Recognize where language models can be useful in real products.', difficulty: 'Beginner', xp: 20, objective: 'Connect common tasks with practical LLM use cases.', type: 'use-case-match', content: '<p>LLMs matter because one language model can support many language tasks through different instructions and application experiences.</p><p>Common uses include chatbots, summarization, translation, code generation, question answering, tutoring and content generation. The surrounding application still matters: the model is a component, not the whole product.</p>', visual: ['Chat', 'Summarize', 'Translate', 'Code', 'Tutor'], matches: [['Customer support assistant', 'Chatbot'], ['Turn a long article into 5 bullets', 'Summarization'], ['Convert a paragraph from Hindi to English', 'Translation'], ['Generate a Python function', 'Code generation'], ['Explain photosynthesis to a student', 'Tutoring']], quiz: { question: 'Which task is a good fit for an LLM?', options: ['Summarizing a document', 'Increasing monitor brightness', 'Replacing a hard drive', 'Measuring room temperature without a sensor'], answer: 0 } },
  { id: 'llm-03', title: 'Meet the Tokens', description: 'See how text can be broken into smaller pieces before a model processes it.', difficulty: 'Beginner', xp: 30, objective: 'Understand tokens and why tokenization is a preprocessing step.', type: 'tokenizer', content: '<p>Before an LLM processes text, the text is represented as <strong>tokens</strong>. A token might be a whole word, part of a word, punctuation, or another piece of text depending on the tokenizer and model.</p><p>For example, <em>“Most famous cheese in France?”</em> could be shown in a simple teaching example as <strong>Most | famous | cheese | in | France | ?</strong>. Real tokenizers can split the same sentence differently.</p><p>This lesson uses an <strong>educational tokenization simulation</strong>, not a real model tokenizer.</p>', visual: ['Text', 'Token', 'Token', 'Token', '...'], quiz: { question: 'Why does an LLM tokenize text?', options: ['To make text easier for the model to process', 'To translate text into English', 'To store text in a database', 'To search Google'], answer: 0 } },
  { id: 'llm-04', title: 'From Tokens to Numbers', description: 'Build intuition for embeddings and vector representations.', difficulty: 'Beginner', xp: 30, objective: 'Understand that tokens can be represented as numerical vectors.', type: 'embeddings', content: '<p>A model cannot directly process the meaning of a word as a human does. Tokens are represented numerically so the model can perform computations with them.</p><p>An <strong>embedding</strong> is a vector representation of information. The values are learned by a model; different models can produce different embeddings.</p><p>The numbers below are an <strong>illustrative vector</strong>, not a real embedding. A useful mental model is: <strong>token → vector representation → relationships in a mathematical space</strong>.</p>', visual: ['cheese', '→', '[ 0.12, -0.55, 1.03, ... ]'], quiz: { question: 'What is an embedding?', options: ['A vector representation of information', 'A database', 'A prompt template', 'A generated answer'], answer: 0 } },
  { id: 'llm-05', title: 'Attention: What Should the Model Focus On?', description: 'Explore how attention helps relate different tokens in a sequence.', difficulty: 'Beginner', xp: 35, objective: 'Understand attention as a way to assign different importance to token relationships.', type: 'attention', content: '<p><strong>Attention</strong> helps a transformer assign different importance to relationships between tokens while processing a sequence.</p><p>For the question <em>“Most famous cheese in France?”</em>, the word <strong>cheese</strong> has useful relationships with words such as <strong>famous</strong> and <strong>France</strong>.</p><p>This is not human-like understanding. It is a mechanism for processing relationships between representations in context.</p>', visual: ['Most', 'famous', 'cheese', 'in', 'France', '?'], quiz: { question: 'Which word is especially useful when answering “Most famous cheese in France?”', options: ['cheese', 'banana', 'car', 'pencil'], answer: 0 } },
  { id: 'llm-06', title: 'How an LLM Generates Text', description: 'Watch a simplified next-token prediction loop build a response.', difficulty: 'Beginner', xp: 35, objective: 'Understand generation as repeated next-token prediction.', type: 'generation', content: '<p>A text-generation LLM produces output <strong>one token at a time</strong>. It uses the tokens already in context to predict what could come next, selects a token, adds it to the context, and predicts again.</p><p>The probabilities in this simulation are deliberately illustrative. They are <strong>not</strong> outputs from GPT, Gemini, Ollama, or any other real model.</p>', visual: ['Input', 'Tokenization', 'Representations', 'Transformer', 'Next token', 'Output'], generation: { prompt: 'The sky is', steps: [{ token: 'blue', probability: 70, alternatives: [['green', 15], ['clear', 8], ['bright', 4]] }, { token: 'and', probability: 52, alternatives: [['very', 20], ['so', 12], ['today', 6]] }, { token: 'clear', probability: 61, alternatives: [['bright', 16], ['wide', 9], ['calm', 5]] }, { token: 'today', probability: 58, alternatives: [['outside', 17], ['above', 11], ['here', 6]] }] }, quiz: { question: 'What is the core idea behind text generation in an LLM?', options: ['Repeatedly predicting the next token from context', 'Looking up every sentence in a database', 'Choosing a random paragraph once', 'Rendering the answer with CSS'], answer: 0 } },
  { id: 'llm-07', title: 'What Are Parameters?', description: 'Understand parameters as learned numerical values inside a model.', difficulty: 'Beginner', xp: 25, objective: 'Understand what parameters are and why model size matters.', type: 'parameters', content: '<p><strong>Parameters</strong> are learned numerical values inside a model. During training, these values are adjusted so the model becomes better at its task.</p><p>Parameter count is one way to describe model size or capacity, but <strong>more parameters does not automatically mean better overall performance</strong>.</p><p>Larger models can potentially provide more capability, while usually requiring more compute, memory and storage.</p>', visual: ['weight', 'weight', 'weight', 'weight', '...'], quiz: { question: 'What is a parameter?', options: ['A learned numerical value in a model', 'A user question', 'A database record', 'A browser setting'], answer: 0 } },
  { id: 'llm-08', title: 'Temperature, Top-k & Top-p', description: 'Experiment with the main generation controls conceptually.', difficulty: 'Beginner', xp: 40, objective: 'Understand how temperature, top-k and top-p influence candidate selection.', type: 'sampling', content: '<p><strong>Temperature</strong> changes how concentrated or spread out a model’s candidate probabilities are. Lower values tend to make selection more predictable; higher values tend to allow more variety.</p><p><strong>Top-k</strong> limits selection to the k most probable candidates. <strong>Top-p</strong> selects the smallest candidate group whose cumulative probability reaches a chosen threshold.</p><p>This is a <strong>generation parameter simulation</strong>. Its probabilities are illustrative, not real LLM inference.</p>', visual: ['Candidates', 'Temperature', 'Top-k', 'Top-p'], sampling: { candidates: [['robot', 0.42], ['lab', 0.25], ['house', 0.16], ['garden', 0.09], ['station', 0.05], ['forest', 0.03]] }, quiz: { question: 'What does a higher temperature generally encourage?', options: ['More varied candidate selection', 'A guaranteed correct answer', 'Fewer tokens in the prompt', 'A larger model'], answer: 0 } }
];

export const finalChallenge = {
  id: 'llm-final', title: 'LLM Fundamentals — Final Challenge', description: 'Prove that you can trace a prompt through the core LLM concepts.', difficulty: 'Challenge', xp: 100, objective: 'Pass with at least 70% by applying the concepts from Missions 01–08.', type: 'final',
  questions: [
    { question: 'What does LLM stand for?', options: ['Large Language Model', 'Learning Logic Machine', 'Language Lookup Memory', 'Large Logic Module'], answer: 0 },
    { question: 'What is a token?', options: ['A piece of text used in processing', 'A database table', 'A model parameter', 'A browser cookie'], answer: 0 },
    { question: 'What is an embedding?', options: ['A vector representation of information', 'A final generated answer', 'A prompt template', 'A search engine'], answer: 0 },
    { question: 'What does attention help a transformer do?', options: ['Relate tokens with different importance in context', 'Search the internet', 'Store every answer', 'Increase screen resolution'], answer: 0 },
    { question: 'Put this simplified generation pipeline in order.', order: ['Input text', 'Tokenization', 'Transformer / attention', 'Next-token prediction', 'Output'], type: 'order' },
    { question: 'Which statement about parameters is correct?', options: ['They are learned numerical values inside a model', 'They are user questions', 'They are database records', 'They are browser settings'], answer: 0 },
    { question: 'What does lower temperature generally do?', options: ['Makes the distribution more concentrated and selection more predictable', 'Adds parameters', 'Removes tokenization', 'Turns the model into a search engine'], answer: 0 },
    { question: 'What does top-k do?', options: ['Limits candidates to the k most probable choices', 'Chooses every candidate', 'Changes model size', 'Converts tokens into English'], answer: 0 },
    { question: 'What does top-p do?', options: ['Chooses the smallest candidate group reaching a probability threshold', 'Always chooses exactly three tokens', 'Changes the number of model parameters', 'Disables attention'], answer: 0 },
    { question: 'In one short sentence, explain what an LLM does when it generates text.', type: 'short', answer: 'predict' }
  ]
};

export const achievements = [
  { id: 'first-step', icon: '↗', title: 'FIRST STEP', description: 'Complete your first lesson.' },
  { id: 'curious-mind', icon: '✦', title: 'CURIOUS MIND', description: 'Complete 3 lessons.' },
  { id: 'ai-explorer', icon: '◆', title: 'AI EXPLORER', description: 'Complete Level 1.' },
  { id: 'token-tamer', icon: '▦', title: 'TOKEN TAMER', description: 'Complete the tokenization mission.' },
  { id: 'attention-seeker', icon: '◎', title: 'ATTENTION SEEKER', description: 'Complete the attention mission.' },
  { id: 'model-thinker', icon: '◈', title: 'MODEL THINKER', description: 'Complete the parameters mission.' },
  { id: 'llm-initiate', icon: '★', title: 'LLM INITIATE', description: 'Complete all LLM Fundamentals missions.' }
];

export const lessons = [...foundationLessons, ...llmLessons, finalChallenge];
