import {phase8Lessons,phase8Achievements} from './phase8.js';
import {foundationLessons,llmLessons,promptLessons,finalChallenge} from './curriculum.js';
import {phase4Lessons} from './phase4.js';import {phase5Lessons} from './phase5.js';import {phase6Lessons} from './phase6.js';import {phase7Lessons} from './phase7.js';
import {loadState,saveState,completeLesson,unlockAchievements,isLevelUnlocked,unlockLevel,markLevelCompleted,recordChallengeScore} from './state.js';
let state=loadState(),active=null,activity=false,quiz=false;const $=s=>document.querySelector(s),esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const all=[...foundationLessons,...llmLessons,...promptLessons,finalChallenge,...phase4Lessons,...phase5Lessons,...phase6Lessons,...phase7Lessons,...phase8Lessons];
const done=()=>phase8Lessons.filter(x=>state.completedLessons.includes(x.id)).length;
function refresh(){state=loadState();render();renderAchievements();updateShell();}function updateShell(){const n=all.filter(x=>state.completedLessons.includes(x.id)).length;$('#header-xp').textContent=`${state.xp} XP`;$('#completed-value').textContent=n;$('#hero-progress').textContent=`${Math.round(n/all.length*100)}%`;}
function render(){const list=$('#agent-list');if(!list)return;const open=isLevelUnlocked(state,8),n=done(),p=Math.round(n/10*100);$('#agent-count').textContent=`${n} / 10`;$?null:0;$('#agent-progress-percent').textContent=`${p}%`;$('#agent-progress-bar').style.width=`${p}%`;$('#agent-locked-note').hidden=open;$('.agents-section')?.classList.toggle('is-locked',!open);const firstNine=phase8Lessons.slice(0,-1).every(x=>state.completedLessons.includes(x.id));list.innerHTML=phase8Lessons.map((x,i)=>{const c=state.completedLessons.includes(x.id),lock=!open||(x.type==='agent-final'&&!firstNine);return `<article class="lesson-card agent-card ${c?'completed':''} ${lock?'locked':''}"><div class="lesson-index">${c?'✓':String(i+1).padStart(2,'0')}</div><div><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p><div class="lesson-tags"><span class="tag">${x.difficulty}</span><span class="tag xp">+${x.xp} XP</span>${x.type==='agent-final'?'<span class="tag challenge">FINAL</span>':''}</div></div><button class="lesson-button" data-agent-lesson="${x.id}" ${lock?'disabled':''}>${c?'Review':lock?'Locked':x.type==='agent-final'?'Start Final Boss':'Start Mission'}</button></article>`}).join('');}
function renderAchievements(){const list=$('#achievement-list');if(!list)return;list.querySelectorAll('[data-phase8]').forEach(x=>x.remove());phase8Achievements.forEach(a=>{const e=document.createElement('article');e.className=`achievement ${state.achievements.includes(a.id)?'unlocked':''}`;e.dataset.phase8=a.id;e.innerHTML=`<div class="achievement-icon">${a.icon}</div><div><h3>${a.title} ${state.achievements.includes(a.id)?'✓':''}</h3><p>${a.description}</p></div>`;list.appendChild(e);});}
function openLesson(id){state=loadState();active=phase8Lessons.find(x=>x.id===id);if(!active||!isLevelUnlocked(state,8))return;if(active.type==='agent-final'&&!phase8Lessons.slice(0,-1).every(x=>state.completedLessons.includes(x.id)))return;activity=false;quiz=active.type!=='agent-final';$('#modal-title').textContent=active.title;$('#modal-description').textContent=active.description;$('#modal-difficulty').textContent=active.difficulty;$('#modal-xp').textContent=`+${active.xp} XP`;$?null:0;$('#modal-objective').innerHTML=`<strong>Learning objective</strong><span>${esc(active.objective)}</span>`;$('#modal-visual').innerHTML=visual(active);$('#modal-content').innerHTML=active.content;$('#modal-interaction').innerHTML=interaction(active);$('#modal-quiz').innerHTML=active.type==='agent-final'?finalUI(active):quizUI(active);$('#complete-button').hidden=active.type==='agent-final';$('#complete-button').disabled=state.completedLessons.includes(id);$('#complete-button').textContent=state.completedLessons.includes(id)?'Mission completed ✓':`Complete mission · +${active.xp} XP`;$('#lesson-modal').hidden=false;$('#modal-close').focus();bind();}
function visual(x){if(x.type==='agent-intro')return `<div class="agent-flow"><button data-stage="0">🎯 GOAL</button><i>↓</i><button data-stage="1">🧠 DECIDE</button><i>↓</i><button data-stage="2">🧰 ACT</button><i>↓</i><button data-stage="3">📊 OBSERVE</button><i>↓</i><button data-stage="4">🧠 NEXT DECISION</button><div id="agent-stage-detail" class="agent-detail">Click a stage.</div></div>`;
if(x.type==='agent-compare')return `<div class="architecture-tabs"><button class="selected" data-arch="llm">LLM</button><button data-arch="rag">RAG</button><button data-arch="agent">AGENT</button></div><div id="architecture-display" class="architecture-display"></div>`;
if(x.type==='tool-shelf')return `<div class="tool-shelf">${x.tools.map((t,i)=>`<button data-tool="${i}">${t[1]}<small>${t[2]}</small></button>`).join('')}</div><div id="tool-detail" class="agent-detail">Select a tool to inspect its interface.</div>`;
if(x.type==='tool-call')return `<div class="tool-call-flow"><div>👤 USER<br><small>287 × 42</small></div><i>↓</i><button id="inspect-call">🧠 LLM → TOOL CALL</button><i>↓</i><div id="call-result">🧰 Calculator<br><small>Result appears here</small></div><i>↓</i><div>💬 FINAL RESPONSE</div></div>`;
if(x.type==='agent-loop')return `<div class="loop-visual"><div class="loop-node">🎯 Goal</div><div class="loop-node">🧠 Decide</div><div class="loop-node">🧰 Act</div><div class="loop-node">📊 Observe</div><div class="loop-node">🧠 Decide again</div><div class="loop-node">💬 Answer</div></div>`;
if(x.type==='planning')return `<div class="plan-board"><strong>Goal: Prepare a study schedule</strong><div id="plan-actions" class="plan-actions">${['Calculate available hours','Search syllabus','Create schedule','Send email','Generate final plan'].map((a,i)=>`<button data-plan="${i}">${a}</button>`).join('')}</div><div id="plan-result" class="agent-detail">Choose the actions that belong in the task.</div></div>`;
if(x.type==='tool-select')return `<div class="selection-game"><div class="request-box" id="tool-request">Choose a request below.</div><div class="tool-choice-grid">${x.requests.map((r,i)=>`<button data-request="${i}">${r[0]}</button>`).join('')}</div><div id="tool-choice-result" class="agent-detail"></div></div>`;
if(x.type==='memory')return `<div class="memory-tabs"><button class="selected" data-memory="context">CONTEXT</button><button data-memory="persistent">PERSISTENT MEMORY</button></div><div id="memory-display" class="agent-detail"></div>`;
if(x.type==='mini-agent')return `<div class="mini-agent"><label>Goal<select id="agent-goal">${x.goals.map(g=>`<option>${g}</option>`).join('')}</select></label><strong>Choose tools</strong><div class="tool-checks">${x.tools.map((t,i)=>`<label><input type="checkbox" value="${i}">${t}</label>`).join('')}</div><button class="secondary-action" id="run-agent">Run simulated agent</button><div class="trace" id="agent-trace">Execution Trace will appear here.</div></div>`;
return `<div class="final-agent-visual"><div>🎯 USER GOAL</div><i>↓</i><div>🤖 AGENT</div><i>↓</i><div>🧠 DECIDE → 🧰 TOOL → 📊 OBSERVE</div><i>↻</i><div>🧠 DECIDE → 💬 ANSWER</div></div>`;}
function interaction(x){if(x.type==='agent-intro')return `<div class="activity-card"><p class="muted small">Example: “Find the best route to college.” Click each stage.</p><div id="intro-feedback" class="visual-feedback"></div></div>`;
if(x.type==='agent-compare')return `<div class="activity-card"><p class="muted small">Which architecture fits? Some real systems combine patterns.</p><div class="scenario-grid">${x.scenarios.map((s,i)=>`<button data-compare-scenario="${i}">${s[0]}</button>`).join('')}</div><div id="compare-feedback" class="visual-feedback"></div></div>`;
if(x.type==='tool-shelf')return `<div class="activity-card"><div class="phase8-note">Educational Simulation · these tools are fictional and local.</div></div>`;
if(x.type==='tool-call')return `<div class="activity-card"><button class="secondary-action" id="run-tool-call">Inspect tool call</button><div id="tool-call-feedback" class="visual-feedback"></div></div>`;
if(x.type==='agent-loop')return `<div class="activity-card"><button class="secondary-action" id="run-loop">Run agent loop</button><div id="loop-feedback" class="visual-feedback"></div><div class="phase8-note">Execution Trace shows concise observable decisions, not hidden chain-of-thought.</div></div>`;
if(x.type==='planning')return `<div class="activity-card"><button class="secondary-action" id="check-plan">Check selected actions</button><div id="plan-feedback" class="visual-feedback"></div></div>`;
if(x.type==='tool-select')return `<div class="activity-card"><div id="selection-feedback" class="visual-feedback"></div></div>`;
if(x.type==='memory')return `<div class="activity-card"><div id="memory-feedback" class="visual-feedback"></div></div>`;
if(x.type==='mini-agent')return `<div class="activity-card"><div id="mini-agent-feedback" class="visual-feedback"></div><div class="phase8-note">Educational Simulation · no real tools or autonomous agent are running.</div></div>`;
return `<div class="activity-card"><strong>Final architecture challenge</strong><p class="muted small">Build the loop, choose tools, handle failure/missing information, and keep permissions controlled.</p><div class="final-options">${x.tools.map((t,i)=>`<label><input type="checkbox" data-final-tool="${i}"> ${t}</label>`).join('')}</div><div class="final-options"><label>Failure handling<select id="f-failure"><option>Retry</option><option>Use another appropriate tool</option><option>Explain that information could not be retrieved</option><option>Pretend the tool succeeded</option></select></label><label>Missing information<select id="f-missing"><option>Say information was not found</option><option>Ask for clarification</option><option>Invent an answer</option></select></label><label>Permission<select id="f-permission"><option>Ask for confirmation before consequential actions</option><option>Unlimited execute permission</option></select></label></div><div class="final-reasons">${x.reasons.map(r=>`<label><input type="checkbox" data-final-reason="${esc(r)}"> ${esc(r)}</label>`).join('')}</div><button class="secondary-action" id="build-agent-final">Build agent loop</button><div id="agent-final-built" class="final-built"></div><button class="primary-button" id="score-agent-final">Evaluate architecture</button><div id="agent-final-score" class="final-score">0%</div><div id="agent-final-feedback" class="visual-feedback"></div></div>`;}
function quizUI(x){return `<h3>🧠 Quick check</h3><p>${esc(x.quiz.question)}</p><div class="quiz-options">${x.quiz.options.map((o,i)=>`<button class="quiz-option" data-agent-answer="${i}">${esc(o)}</button>`).join('')}</div><div class="quiz-feedback" id="agent-quiz-feedback"></div>`;}
function finalUI(){return `<h3>🧠 Final architecture challenge</h3><p>Design an AI assistant for a software development team that can answer questions, use documentation/search/calculation/code tools, and work through multi-step tasks.</p><div class="phase8-note">Passing score: 70%. Good safety and failure handling matter.</div>`;}
function completeCurrent(){if(!active)return;state=loadState();if(state.completedLessons.includes(active.id)){activity=true;return;}if(!activity||!quiz)return;completeLesson(state,active.id,active.xp);const newly=unlockAchievements(state,[...foundationLessons,...llmLessons,...promptLessons,finalChallenge,...phase4Lessons,...phase5Lessons,...phase6Lessons,...phase7Lessons,...phase8Lessons]);if(phase8Lessons.every(x=>state.completedLessons.includes(x.id))){unlockLevel(state,9);markLevelCompleted(state,8);}saveState(state);window.dispatchEvent(new Event('ailearn-state-updated'));showReward(active.xp,newly);$('#lesson-modal').hidden=true;refresh();}
function showReward(xp,newly){$('#reward-title').textContent='Mission Complete!';$('#reward-copy').textContent=`+${xp} XP${newly.length?` · ${newly.length} achievement${newly.length>1?'s':''} unlocked`:''}`;$('#reward-toast').hidden=false;setTimeout(()=>$('#reward-toast').hidden=true,2600);}
function bind(){document.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>{activity=true;const m=['The user goal is the target outcome.','The model/application selects a useful next action.','Act means invoke an available capability.','Observe means inspect the returned result.','The next decision can depend on that result.'];$('#agent-stage-detail').textContent=m[+b.dataset.stage];});
document.querySelectorAll('[data-arch]').forEach(b=>b.onclick=()=>{activity=true;const a={llm:'USER → LLM → ANSWER',rag:'USER → RETRIEVE → CONTEXT → LLM → ANSWER',agent:'USER → AGENT → DECIDE → TOOL → OBSERVE → DECIDE → ANSWER'};document.querySelectorAll('[data-arch]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('#architecture-display').textContent=a[b.dataset.arch];});$('#architecture-display')?.click();
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{activity=true;const t=active.tools[+b.dataset.tool];$('#tool-detail').innerHTML=`<strong>${t[1]}</strong><br>Purpose: ${t[2]}<br>Input: ${t[3]}<br>Output: ${t[4]}`;});
$('#inspect-call')?.addEventListener('click',()=>{activity=true;$('#call-result').innerHTML='<strong>TOOL RESULT</strong><br>{ result: 12054 }';$('#tool-call-feedback').textContent='Tool call: calculator({ expression: "287 * 42" }) → runtime executes → result 12054 → model formats the answer.';});
$('#run-tool-call')?.addEventListener('click',()=>{$('#inspect-call').click();});
$('#run-loop')?.addEventListener('click',()=>{activity=true;$('#loop-feedback').innerHTML='🎯 Goal received → 🧠 Decide: current weather is needed → 🧰 Weather Tool → 📊 Tool returned 28°C, rain probability 70% → 🧠 Decide → 💬 Carry an umbrella.';});
$('#check-plan')?.addEventListener('click',()=>{const chosen=[...document.querySelectorAll('[data-plan].selected')].length;activity=true;$('#plan-feedback').textContent=chosen>=3?'Reasonable plan: calculate available hours, search syllabus, create schedule, then generate the final plan. Multiple valid plans can work.':'Select several actions that actually contribute to the study-schedule goal.';});document.querySelectorAll('[data-plan]').forEach(b=>b.onclick=()=>{activity=true;b.classList.toggle('selected');});
document.querySelectorAll('[data-request]').forEach(b=>b.onclick=()=>{activity=true;const r=active.requests[+b.dataset.request];$('#tool-request').textContent=r[0];$('#tool-choice-result').textContent=`Expected capability: ${r[1]}. A clear tool description/schema helps the model make this choice.`;});
document.querySelectorAll('[data-memory]').forEach(b=>b.onclick=()=>{activity=true;document.querySelectorAll('[data-memory]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('#memory-display').innerHTML=b.dataset.memory==='context'?'CONTEXT: “My favorite language is Python.” → available while included in the current input.':'PERSISTENT MEMORY: preferred_language = Python → application stores it and retrieves it later.';});$('#memory-display')?.click();
$('#run-agent')?.addEventListener('click',()=>{const tools=[...document.querySelectorAll('#modal-visual input[type=checkbox]:checked')].map(x=>x.parentElement.textContent.trim());activity=true;$('#agent-trace').innerHTML=`<b>Execution Trace</b><br>1. Goal received: ${esc($('#agent-goal').value)}<br>2. Selected tools: ${esc(tools.join(', ')||'none')}<br>3. Decide: choose an available capability<br>4. Tool result: simulated result returned<br>5. Decide: incorporate result<br>6. Final answer generated locally<br><small>Educational Simulation · no hidden reasoning shown.</small>`;});
document.querySelectorAll('[data-compare-scenario]').forEach(b=>b.onclick=()=>{activity=true;const s=active.scenarios[+b.dataset.compareScenario];$('#compare-feedback').textContent=`This scenario can use: ${s[1]}. Real applications may combine LLM, RAG, and agent patterns.`;});
$('#build-agent-final')?.addEventListener('click',()=>{activity=true;$('#agent-final-built').textContent='USER → AGENT → DECIDE → TOOL → OBSERVE → DECIDE → FINAL ANSWER';});$('#score-agent-final')?.addEventListener('click',()=>{const tools=document.querySelectorAll('[data-final-tool]:checked').length;const reasons=document.querySelectorAll('[data-final-reason]:checked').length;const safe=$('#f-failure').value!=='Pretend the tool succeeded'&&$('#f-missing').value!=='Invent an answer'&&$('#f-permission').value!=='Unlimited execute permission';let score=Math.min(100,30+(tools?20:0)+(reasons>=3?25:reasons*5)+(safe?25:0));recordChallengeScore(state,'agent-final',score);saveState(state);activity=score>=70;quiz=score>=70;$('#agent-final-score').textContent=`${score}%`;$('#agent-final-feedback').textContent=score>=70?'Architecture passes. Tool use, observable execution, failure handling, and controlled permissions are represented.':'Keep improving the design: include useful tools, safe failure/missing-information handling, and controlled permissions.';});
document.querySelectorAll('[data-agent-answer]').forEach(b=>b.onclick=()=>{const ok=+b.dataset.agentAnswer===active.quiz.answer;quiz=ok;document.querySelectorAll('[data-agent-answer]').forEach(x=>x.disabled=true);$('#agent-quiz-feedback').textContent=ok?'✓ Correct.':'Not quite — review the lesson and try the mission again.';});}
document.addEventListener('click',e=>{const b=e.target.closest('[data-agent-lesson]');if(b)openLesson(b.dataset.agentLesson);if(e.target.closest('#complete-button'))completeCurrent();if(e.target.closest('#modal-close'))$('#lesson-modal').hidden=true;});window.addEventListener('ailearn-state-updated',refresh);render();renderAchievements();updateShell();