import { phase7Lessons, phase7Achievements, ragKnowledgeBase } from './phase7.js';
import { foundationLessons, llmLessons, promptLessons, finalChallenge } from './curriculum.js';
import { phase4Lessons } from './phase4.js';
import { phase5Lessons } from './phase5.js';
import { phase6Lessons } from './phase6.js';
import { loadState, saveState, completeLesson, unlockAchievements, isLevelUnlocked, unlockLevel, markLevelCompleted, recordChallengeScore } from './state.js';

let state=loadState(),active=null,activity=false,quiz=false;
const $=s=>document.querySelector(s),esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const all=[...foundationLessons,...llmLessons,...promptLessons,finalChallenge,...phase4Lessons,...phase5Lessons,...phase6Lessons,...phase7Lessons];
const done=()=>phase7Lessons.filter(x=>state.completedLessons.includes(x.id)).length;
const unlocked=()=>isLevelUnlocked(state,7);
function refresh(){state=loadState();render();renderAchievements();updateShell();}
function updateShell(){const n=all.filter(x=>state.completedLessons.includes(x.id)).length;$('#header-xp').textContent=`${state.xp} XP`;$('#completed-value').textContent=n;$('#hero-progress').textContent=`${Math.round(n/all.length*100)}%`;}
function render(){const list=$('#rag-list');if(!list)return;const open=unlocked(),n=done(),p=Math.round(n/10*100);$('#rag-count').textContent=`${n} / 10`;$('#rag-progress-percent').textContent=`${p}%`;$('#rag-progress-bar').style.width=`${p}%`;$('#rag-locked-note').hidden=open;$('.rag-section')?.classList.toggle('is-locked',!open);const firstNine=phase7Lessons.slice(0,-1).every(x=>state.completedLessons.includes(x.id));list.innerHTML=phase7Lessons.map((x,i)=>{const complete=state.completedLessons.includes(x.id),lock=!open||(x.type==='rag-final'&&!firstNine);return `<article class="lesson-card rag-card ${complete?'completed':''} ${lock?'locked':''}"><div class="lesson-index">${complete?'✓':String(i+1).padStart(2,'0')}</div><div><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p><div class="lesson-tags"><span class="tag">${x.difficulty}</span><span class="tag xp">+${x.xp} XP</span>${x.type==='rag-final'?'<span class="tag challenge">FINAL</span>':''}</div></div><button class="lesson-button" data-rag-lesson="${x.id}" ${lock?'disabled':''}>${complete?'Review':lock?'Locked':x.type==='rag-final'?'Start Final Boss':'Start Mission'}</button></article>`}).join('');}
function renderAchievements(){const list=$('#achievement-list');if(!list)return;list.querySelectorAll('[data-phase7-achievement]').forEach(n=>n.remove());phase7Achievements.forEach(a=>{const el=document.createElement('article');el.className=`achievement ${state.achievements.includes(a.id)?'unlocked':''}`;el.dataset.phase7Achievement=a.id;el.innerHTML=`<div class="achievement-icon">${a.icon}</div><div><h3>${a.title} ${state.achievements.includes(a.id)?'✓':''}</h3><p>${a.description}</p></div>`;list.appendChild(el);});}
function openLesson(id){state=loadState();active=phase7Lessons.find(x=>x.id===id);if(!active||!unlocked())return;if(active.type==='rag-final'&&!phase7Lessons.slice(0,-1).every(x=>state.completedLessons.includes(x.id)))return;activity=false;quiz=active.type!=='rag-final';$('#modal-title').textContent=active.title;$('#modal-description').textContent=active.description;$('#modal-difficulty').textContent=active.difficulty;$('#modal-xp').textContent=`+${active.xp} XP`;$('#modal-objective').innerHTML=`<strong>Learning objective</strong><span>${esc(active.objective)}</span>`;$('#modal-visual').innerHTML=visual(active);$('#modal-content').innerHTML=active.content;$('#modal-interaction').innerHTML=interaction(active);$('#modal-quiz').innerHTML=active.type==='rag-final'?finalUI(active):quizUI(active);$('#complete-button').hidden=active.type==='rag-final';$('#complete-button').disabled=state.completedLessons.includes(id);$('#complete-button').textContent=state.completedLessons.includes(id)?'Mission completed ✓':`Complete mission · +${active.xp} XP`;$('#lesson-modal').hidden=false;$('#modal-close').focus();bind();}
function visual(x){if(x.type==='rag-why')return `<div class="rag-flow"><div class="rag-node">👤 USER<br><small>Private document question</small></div><i>↓</i><div class="rag-node">🤖 LLM<br><small>Without supplied document context</small></div><i>↓</i><div class="rag-node">?</div><div class="rag-branch"><span>RAG pattern</span><b>QUESTION → RETRIEVE → CONTEXT → LLM → ANSWER</b></div></div>`;
if(x.type==='rag-compare')return `<div class="rag-compare"><div class="rag-compare-tabs"><button class="selected" data-mode="only">LLM ONLY</button><button data-mode="rag">RAG</button></div><div id="compare-mode" class="compare-panel"></div></div>`;
if(x.type==='rag-pipeline')return `<div class="rag-pipeline"><div><span class="pipeline-label">📥 INGESTION TIME</span><div class="pipeline-row">${['📄 Documents','✂️ Chunking','🧠 Embeddings','🗄 Vector Store'].map((n,i)=>`<button data-pipe="${i}">${n}</button>`).join('<i>↓</i>')}</div></div><div><span class="pipeline-label">⚡ QUERY TIME</span><div class="pipeline-row">${['👤 User Question','🧠 Query Embedding','🔎 Retrieval','📄 Relevant Chunks','📝 Context + Question','🤖 LLM','💬 Answer'].map((n,i)=>`<button data-query-pipe="${i}">${n}</button>`).join('<i>↓</i>')}</div></div><div class="pipeline-detail" id="pipeline-detail">Click any step to inspect it.</div></div>`;
if(x.type==='rag-ingest')return `<div class="ingest-sim"><div class="ingest-stage active" data-stage="0">📄<span>Load document</span></div><div class="ingest-stage" data-stage="1">✂️<span>Chunk</span></div><div class="ingest-stage" data-stage="2">🧠<span>Embed</span></div><div class="ingest-stage" data-stage="3">🗄<span>Store</span></div><div class="ingest-output" id="ingest-output">AI Engineering Handbook loaded.</div></div>`;
if(x.type==='rag-retrieve')return `<div class="retrieve-sim"><label>Query<input id="rag-query" class="search-input" value="How does an LLM application retrieve information?" aria-label="Retrieval query"></label><div class="topk"><span>Top-K</span><button data-k="1">1</button><button class="selected" data-k="3">3</button><button data-k="5">5</button></div><div id="rag-results" class="search-results"></div></div>`;
if(x.type==='rag-ground')return `<div class="ground-sim"><div class="ground-grid"><div><span class="sim-label">USER QUESTION</span><div class="sim-box">What is our refund policy?</div></div><div><span class="sim-label">RETRIEVED CONTEXT</span><div class="sim-box" id="ground-context">Refunds are available within 30 days for eligible purchases.</div></div></div><div class="model-input" id="model-input">SYSTEM: You are a helpful support assistant.<br><br>CONTEXT: Refunds are available within 30 days for eligible purchases.<br><br>USER: What is our refund policy?</div></div>`;
if(x.type==='rag-failures')return `<div class="failure-sim"><div class="failure-list">${['✂️ Bad chunking','🔎 Wrong retrieval','❓ Missing information','📚 Too much context','🕰 Stale information','⚠️ Conflicting sources'].map((n,i)=>`<button data-failure="${i}">${n}</button>`).join('')}</div><div class="failure-detail" id="failure-detail">Select a failure mode to break the system.</div></div>`;
if(x.type==='rag-builder')return `<div class="arch-builder"><div class="builder-instructions">Click components in the correct conceptual order. The builder separates ingestion from the query path.</div><div class="builder-components">${['📄 Documents','✂️ Chunker','🧠 Embedding Model','🗄 Vector Store','👤 User','🔎 Retriever','📝 Context Builder','🤖 LLM','💬 Response'].map((n,i)=>`<button data-component="${i}" data-name="${n}">${n}</button>`).join('')}</div><div class="builder-built" id="builder-built"><span class="muted small">Your architecture will appear here.</span></div><div class="builder-query-note">USER QUESTION → RETRIEVER → VECTOR STORE → RELEVANT CHUNKS → CONTEXT BUILDER → LLM</div><button class="secondary-action" id="builder-reset">Reset builder</button></div>`;
if(x.type==='mini-rag')return `<div class="mini-rag"><div class="mini-kb"><strong>📚 Knowledge Base</strong><div class="kb-grid">${ragKnowledgeBase.map(d=>`<button data-kb="${d.id}">${d.title}<small>${d.section}</small></button>`).join('')}</div></div><div class="mini-progress" id="mini-progress"><span>1. Inspect knowledge base</span><span>2. Index</span><span>3. Ask</span><span>4. Retrieve</span><span>5. Context</span><span>6. Generate</span><span>7. Sources</span></div><div class="mini-query"><input id="mini-query" class="search-input" value="What is retrieval augmented generation?" aria-label="Mini RAG question"><button class="secondary-action" id="mini-run">Run Mini RAG</button></div><div id="mini-output" class="mini-output">Run the simulation to trace one complete RAG request.</div></div>`;
return `<div class="rag-final-visual"><div class="final-lane"><span>📥 INGESTION</span><b>DOCUMENTS → CHUNKS → EMBEDDINGS → VECTOR STORE</b></div><div class="final-lane"><span>⚡ QUERY</span><b>QUESTION → QUERY EMBEDDING → RETRIEVAL → TOP CHUNKS → CONTEXT → LLM → ANSWER → SOURCES</b></div></div>`;}
function interaction(x){if(x.type==='rag-why')return `<div class="activity-card"><strong>Scenario check</strong><div class="scenario-grid">${['Company HR handbook','Product documentation','College notes','Recently updated policy'].map((n,i)=>`<button data-scenario="${i}">${n}</button>`).join('')}</div><div id="scenario-feedback" class="visual-feedback"></div></div>`;
if(x.type==='rag-compare')return `<div class="activity-card"><strong>Compare the same question</strong><p class="muted small">According to our employee handbook, how many vacation days are available?</p><div id="compare-explanation" class="visual-feedback"></div></div>`;
if(x.type==='rag-pipeline')return `<div class="activity-card"><div id="pipeline-feedback" class="visual-feedback">Inspect both ingestion and query-time paths.</div></div>`;
if(x.type==='rag-ingest')return `<div class="activity-card"><button class="secondary-action" id="run-ingest">Run ingestion step-by-step</button><div id="ingest-feedback" class="visual-feedback"></div><div class="phase7-note">Educational Simulation · vectors are illustrative.</div></div>`;
if(x.type==='rag-retrieve')return `<div class="activity-card"><button class="secondary-action" id="run-retrieve">Run simulated retrieval</button><div id="retrieve-feedback" class="visual-feedback"></div><div class="phase7-note">Illustrative ranking only — not a real embedding model.</div></div>`;
if(x.type==='rag-ground')return `<div class="activity-card"><label class="context-toggle"><input id="include-context" type="checkbox" checked> Include retrieved context in model input</label><button class="secondary-action" id="run-ground">Build model input</button><div id="ground-feedback" class="visual-feedback"></div></div>`;
if(x.type==='rag-failures')return `<div class="activity-card"><p class="muted small">Choose a failure, diagnose it, then repair the design.</p><button class="secondary-action" id="repair-failure">Repair selected issue</button><div id="failure-feedback" class="visual-feedback"></div></div>`;
if(x.type==='rag-builder')return `<div class="activity-card"><div id="builder-feedback" class="visual-feedback"></div></div>`;
if(x.type==='mini-rag')return `<div class="activity-card"><div id="mini-feedback" class="visual-feedback"></div></div>`;
return `<div class="activity-card"><strong>Final architecture challenge</strong><p class="muted small">Select the design, justify it, build the query path, and evaluate.</p><div class="final-options"><label>Documents<select id="f-doc"><option>Chunks</option><option>Whole documents</option></select></label><label>Representation<select id="f-rep"><option>Embeddings</option><option>Raw text only</option></select></label><label>Retrieval<select id="f-ret"><option>Semantic/vector retrieval</option><option>Exact keyword lookup</option></select></label><label>Storage<select id="f-store"><option>Vector store</option><option>Traditional file storage</option></select></label><label>Sources<select id="f-src"><option>Show retrieved sources</option><option>Don't show sources</option></select></label><label>Missing info<select id="f-missing"><option>Say the information was not found</option><option>Pretend you know</option><option>Ask for clarification</option><option>Fall back to another source</option></select></label></div><div class="final-reasons">${x.reasons.map(r=>`<label><input type="checkbox" data-final-reason="${esc(r)}"> ${esc(r)}</label>`).join('')}</div><button class="secondary-action" id="build-rag-final">Build query pipeline</button><div id="rag-final-built" class="final-built"></div><button class="primary-button" id="score-rag-final">Evaluate architecture</button><div id="rag-final-score" class="final-score">0%</div><div id="rag-final-feedback" class="visual-feedback"></div></div>`;}
function quizUI(x){return `<h3>🧠 Quick check</h3><p>${esc(x.quiz.question)}</p><div class="quiz-options">${x.quiz.options.map((o,i)=>`<button class="quiz-option" data-rag-answer="${i}">${esc(o)}</button>`).join('')}</div><div class="quiz-feedback" id="rag-quiz-feedback"></div>`;}
function finalUI(){return `<h3>🧠 Final architecture challenge</h3><p>Design a documentation assistant that retrieves relevant internal knowledge and gives the LLM enough context to answer responsibly.</p><div class="phase7-note">Passing score: 70%. Reasonable retrieval/storage tradeoffs can receive credit.</div>`;}
function retrieve(query,k){const terms=query.toLowerCase().split(/\W+/).filter(Boolean);return ragKnowledgeBase.map(d=>{const text=(d.title+' '+d.text+' '+d.tags.join(' ')).toLowerCase();let score=0;terms.forEach(t=>{if(text.includes(t))score+=d.tags.includes(t)?3:1;});if(/retrieve|retrieval|rag|generation|context/.test(query.toLowerCase())&&d.tags.some(t=>['retrieval','rag','generation','context'].includes(t)))score+=2;return {...d,score};}).sort((a,b)=>b.score-a.score||a.id.localeCompare(b.id)).slice(0,k);}
function completeCurrent(){if(!active)return;state=loadState();if(state.completedLessons.includes(active.id)){activity=true;return;}if(!activity||!quiz)return;completeLesson(state,active.id,active.xp);const newly=unlockAchievements(state,[...foundationLessons,...llmLessons,...promptLessons,finalChallenge,...phase4Lessons,...phase5Lessons,...phase6Lessons,...phase7Lessons]);if(phase7Lessons.every(x=>state.completedLessons.includes(x.id))){unlockLevel(state,8);markLevelCompleted(state,7);}saveState(state);window.dispatchEvent(new Event('ailearn-state-updated'));showReward(active.xp,newly.length);refresh();$('#complete-button').disabled=true;$('#complete-button').textContent='Mission completed ✓';}
function showReward(xp,n){$('#reward-title').textContent='Mission Complete!';$('#reward-copy').textContent=`+${xp} XP${n?` · ${n} achievement${n>1?'s':''} unlocked`:''}`;const t=$('#reward-toast');t.hidden=false;setTimeout(()=>{t.hidden=true;},2600);}
function bind(){const m=$('#lesson-modal');m.querySelectorAll('[data-scenario]').forEach(b=>b.addEventListener('click',()=>{activity=true;$('#scenario-feedback').textContent='An LLM does not automatically have access to the contents of a private document. The application must supply relevant information through context or another mechanism.';}));
m.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{m.querySelectorAll('[data-mode]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');const rag=b.dataset.mode==='rag';$('#compare-mode').innerHTML=rag?'<strong>RAG simulation</strong><p>Retrieved: Employee Handbook → Leave Policy → Section 4</p><div class="sim-answer">According to the retrieved policy, eligible employees receive the vacation allowance described in Section 4.</div><small>Simulated response · retrieved context supplied at generation time.</small>':'<strong>LLM-only simulation</strong><div class="sim-answer">I don’t have access to your employee handbook.</div><small>No private handbook context was supplied.</small>';$('#compare-explanation').textContent=rag?'RAG adds an application retrieval step and provides selected context to the model.':'LLM-only receives the question and prompt, but no retrieved handbook context.';activity=true;}));
if($('#compare-mode'))$('#compare-mode').innerHTML='<strong>LLM-only simulation</strong><div class="sim-answer">I don’t have access to your employee handbook.</div><small>No private handbook context was supplied.</small>';
m.querySelectorAll('[data-pipe],[data-query-pipe]').forEach(b=>b.addEventListener('click',()=>{const labels=['Documents are source material prepared for indexing.','Chunking splits material into retrievable pieces.','Embeddings create learned numerical representations for comparison.','A vector store/index keeps representations and associated information.','The user supplies the question that drives retrieval.','A query representation lets the retrieval system compare the question with indexed representations.','Retrieval ranks candidates and selects relevant information.','These are the chunks selected for the current question.','The application combines the question with selected context for generation.','The LLM generates from its learned capabilities plus the supplied input.','The answer is the generated output; it can optionally expose sources.'];const i=b.dataset.pipe!==undefined?+b.dataset.pipe:+b.dataset.queryPipe+4;$('#pipeline-detail').innerHTML=`<strong>${esc(b.textContent)}</strong><p>${labels[i]}</p>`;activity=true;}));
$('#run-ingest')?.addEventListener('click',()=>{const stages=['📄 AI Engineering Handbook loaded.','✂️ Split into 4 focused chunks: introduction, LLM architecture, retrieval, evaluation.','🧠 Illustrative vectors created for each chunk: [0.71, 0.23, 0.82…] etc.','🗄 Stored records now contain vector + original text + source + section metadata.'];$('#ingest-feedback').textContent=stages.join(' → ');document.querySelectorAll('.ingest-stage').forEach((s,j)=>s.classList.toggle('active',j===3));$('#ingest-output').textContent=stages[3];activity=true;});
const renderRetrieve=()=>{const q=$('#rag-query')?.value||'';const k=+(document.querySelector('.topk button.selected')?.dataset.k||3);const rows=retrieve(q,k);$('#rag-results').innerHTML=rows.map((r,i)=>`<button class="search-result selected-result"><strong>${i+1}. ${esc(r.title)}</strong><small>Illustrative similarity: ${Math.min(0.98,0.55+r.score*.06).toFixed(2)} · ${esc(r.section)}</small><span>${esc(r.text)}</span></button>`).join('');};
m.querySelectorAll('[data-k]').forEach(b=>b.addEventListener('click',()=>{m.querySelectorAll('[data-k]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');renderRetrieve();activity=true;}));$('#run-retrieve')?.addEventListener('click',()=>{renderRetrieve();$('#retrieve-feedback').textContent='Top-K changes how many ranked candidates continue as context. The scores are illustrative.';activity=true;});$('#rag-query')?.addEventListener('input',renderRetrieve);if($('#rag-results'))renderRetrieve();
$('#run-ground')?.addEventListener('click',()=>{const include=$('#include-context').checked;$('#model-input').innerHTML=include?'SYSTEM: You are a helpful support assistant.<br><br>CONTEXT: Refunds are available within 30 days for eligible purchases.<br><br>USER: What is our refund policy?':'SYSTEM: You are a helpful support assistant.<br><br>USER: What is our refund policy?';$('#ground-feedback').textContent=include?'Context included: generation has the retrieved policy available in the model input.':'⚠ Missing context: retrieval happened, but the selected evidence was not incorporated into the model input.';activity=true;});
let selectedFailure=-1;m.querySelectorAll('[data-failure]').forEach(b=>b.addEventListener('click',()=>{selectedFailure=+b.dataset.failure;const msgs=[['Bad chunking','The refund sentence is split across a boundary, weakening the retrievable unit.'],['Wrong retrieval','Irrelevant shipping, warranty, and company-history chunks were selected.'],['Missing information','The retrieved policy contains no rule for international orders.'],['Too much context','Twenty chunks introduce noise, context usage, and possible conflicts.'],['Stale information','The index returned a 2023 policy while the current policy is from 2026.'],['Conflicting sources','Two sources disagree: 30 days versus 14 days. Application logic should inspect metadata/recency or flag uncertainty.']];$('#failure-detail').innerHTML=`<strong>${msgs[selectedFailure][0]}</strong><p>${msgs[selectedFailure][1]}</p>`;activity=true;}));$('#repair-failure')?.addEventListener('click',()=>{if(selectedFailure<0){$('#failure-feedback').textContent='Select a failure mode first.';return;}$('#failure-feedback').textContent=['Repair by preserving context across chunk boundaries and testing chunking.','Repair by improving retrieval/ranking and validating relevance.','Do not invent the missing rule; say it was not found, ask, or use another source.','Reduce or rerank context so useful evidence is prioritized.','Refresh the index/source and track document timestamps.','Use metadata/recency, retrieve more evidence, or flag uncertainty rather than blindly choosing.'][selectedFailure];activity=true;});
let build=[];const expected=['📄 Documents','✂️ Chunker','🧠 Embedding Model','🗄 Vector Store','👤 User','🔎 Retriever','📝 Context Builder','🤖 LLM','💬 Response'];const renderBuild=()=>{$('#builder-built').innerHTML=build.length?build.map((n,i)=>`<span>${esc(n)}</span>${i<build.length-1?'<b>↓</b>':''}`).join(''):'<span class="muted small">Your architecture will appear here.</span>';};m.querySelectorAll('[data-component]').forEach(b=>b.addEventListener('click',()=>{const n=b.dataset.name;if(n===expected[build.length]){build.push(n);renderBuild();$('#builder-feedback').textContent=build.length===expected.length?'Core components connected in a coherent sequence.':'Good connection — continue the architecture.';}else{$('#builder-feedback').textContent=`Place ${expected[build.length]} next. Think about ingestion first, then the query-time path.`;}activity=build.length===expected.length;}));$('#builder-reset')?.addEventListener('click',()=>{build=[];renderBuild();activity=false;});
$('#mini-run')?.addEventListener('click',()=>{const q=$('#mini-query').value;const rows=retrieve(q,3);$('#mini-output').innerHTML=`<div class="mini-step">📥 INDEX: 10 fictional handbook chunks → illustrative embeddings → local simulated vector store.</div><div class="mini-step">❓ QUERY: ${esc(q)}</div><div class="mini-step">🔎 RETRIEVAL: ${rows.map(r=>`<strong>${esc(r.title)}</strong>`).join(' · ')}</div><div class="mini-step">📝 CONTEXT: The selected chunks are assembled with the question for the simulated model input.</div><div class="mini-step">🤖 GENERATION: RAG retrieves relevant external information and provides selected context to a generative model before producing an answer.</div><div class="mini-step">📚 SOURCES: ${rows.map(r=>`📄 ${esc(r.title)}`).join(' · ')}</div><small>Educational Simulation · retrieval and generation are deterministic/local, not real AI inference.</small>`;$('#mini-feedback').textContent='You traced the complete ingestion → retrieval → context → generation → sources loop.';activity=true;});
m.querySelectorAll('[data-kb]').forEach(b=>b.addEventListener('click',()=>{const d=ragKnowledgeBase.find(x=>x.id===b.dataset.kb);b.classList.add('inspected');$('#mini-feedback').textContent=`${d.title}: ${d.text}`;activity=true;}));
$('#build-rag-final')?.addEventListener('click',()=>{const d=$('#f-doc').value,r=$('#f-rep').value,s=$('#f-ret').value,st=$('#f-store').value;$('#rag-final-built').innerHTML=`<div>📄 ${d}</div><div>↓</div><div>🧠 ${r}</div><div>↓</div><div>🔎 ${s}</div><div>↓</div><div>📝 TOP RELEVANT CHUNKS → CONTEXT + QUESTION → 🤖 LLM → 💬 ANSWER</div>`;activity=true;});
$('#score-rag-final')?.addEventListener('click',()=>{const checks=[$('#f-doc').value==='Chunks',$('#f-rep').value==='Embeddings',$('#f-ret').value==='Semantic/vector retrieval',$('#f-store').value==='Vector store',$('#f-src').value==='Show retrieved sources',$('#f-missing').value!=='Pretend you know',document.querySelectorAll('[data-final-reason]:checked').length>=4,$('#rag-final-built').textContent.trim().length>0];const score=Math.round(checks.filter(Boolean).length/checks.length*100);$('#rag-final-score').textContent=`${score}%`;$('#rag-final-feedback').textContent=score>=70?'Architecture passes. Retrieval is connected to context and generation, with responsible handling of sources/missing information.':'Keep refining the architecture: connect retrieval to context, use a coherent index, and handle uncertainty.';state=loadState();recordChallengeScore(state,'rag-final',score);saveState(state);if(score>=70){activity=true;quiz=true;completeCurrent();}});
m.querySelectorAll('[data-rag-answer]').forEach(b=>b.addEventListener('click',()=>{const ok=+b.dataset.ragAnswer===active.quiz.answer;m.querySelectorAll('[data-rag-answer]').forEach(x=>x.disabled=true);$('#rag-quiz-feedback').textContent=ok?'Correct — concept locked in.':'Not quite. Re-read the mission and try the idea again.';quiz=ok;activity=activity||ok;}));
$('#complete-button')?.addEventListener('click',completeCurrent);}
$('#rag-list')?.addEventListener('click',e=>{const b=e.target.closest('[data-rag-lesson]');if(b&&!b.disabled)openLesson(b.dataset.ragLesson);});$('#modal-close')?.addEventListener('click',()=>{$('#lesson-modal').hidden=true;active=null;});window.addEventListener('ailearn-state-updated',refresh);refresh();