export const phase7Lessons = [
  {id:'rag-01',title:'Why Does RAG Exist?',description:'See why applications sometimes need to retrieve external information before asking an LLM to answer.',difficulty:'Beginner',xp:20,type:'rag-why',objective:'Understand the problem RAG addresses without treating it as the only way to provide external knowledge.',content:'<p>An LLM can generate from learned model knowledge, instructions, and context supplied at request time. But an application may need information from a private handbook, product manual, college notes, or recently updated source.</p><p>RAG is one application pattern for this problem: retrieve relevant information, then provide that selected context to a generative model.</p><p><strong>Important:</strong> RAG does not eliminate hallucinations and is not the only way to provide external knowledge.</p>',quiz:{question:'Why might an application use RAG?',options:['To retrieve relevant external information and provide it as context to generation','To retrain the model for every document update','Because an LLM automatically reads every private database','To replace generation with embeddings'],answer:0}},
  {id:'rag-02',title:'RAG vs LLM-Only',description:'Compare the same question with no retrieved context and with application-provided context.',difficulty:'Beginner',xp:25,type:'rag-compare',objective:'Explain the key difference between an LLM-only flow and retrieval-augmented generation.',content:'<p>LLM-only: <strong>user → prompt → LLM → answer</strong>. RAG adds a retrieval stage: <strong>user → query → retrieval → relevant context → LLM → answer</strong>.</p><p>The important difference is not “database versus no database.” It is that the application retrieves selected information and supplies it to the model at generation time.</p><p>The responses below are simulated.</p>',quiz:{question:'What does RAG add to the LLM-only flow?',options:['Application-provided retrieved context before generation','Automatic model retraining','A guarantee of factual answers','A requirement to use a specific vector database'],answer:0}},
  {id:'rag-03',title:'The RAG Pipeline',description:'Open up the ingestion and query-time paths and inspect every major arrow.',difficulty:'Intermediate',xp:35,type:'rag-pipeline',objective:'Distinguish knowledge ingestion from query-time retrieval and generation.',content:'<p>RAG often has two broad stages. <strong>Ingestion time:</strong> documents are parsed, chunked, embedded, and indexed. <strong>Query time:</strong> a user question is represented, relevant chunks are retrieved, context is assembled, and an LLM generates an answer.</p><p>Different systems can vary: keyword retrieval, metadata filters, hybrid search, reranking, and other strategies can participate.</p>',quiz:{question:'Which is a query-time step?',options:['Retrieve relevant chunks for a user question','Chunk every source document again for each answer','Train the LLM on every document','Delete the original documents'],answer:0}},
  {id:'rag-04',title:'From Documents to Knowledge',description:'Run a local ingestion simulation from a handbook to chunks, illustrative vectors, and stored metadata.',difficulty:'Intermediate',xp:35,type:'rag-ingest',objective:'Understand how RAG knowledge is prepared and indexed before a user asks a question.',content:'<p>Before retrieval can happen, applications commonly prepare source material. A simplified flow is <strong>document → parse → chunk → embed → store</strong>.</p><p>A useful index keeps a representation alongside the original text and metadata such as source or section. The vectors shown here are illustrative, not real embedding outputs.</p>',quiz:{question:'Why can stored retrieval records include original text and metadata?',options:['So retrieved vectors can be mapped back to useful source information','Because vectors automatically contain the full original document','Because metadata replaces retrieval','Because every vector must be human-readable'],answer:0}},
  {id:'rag-05',title:'Retrieve the Right Context',description:'Run a simulated semantic retrieval ranking and see how Top-K changes the selected context.',difficulty:'Intermediate',xp:40,type:'rag-retrieve',objective:'Understand ranking, Top-K, and the tradeoff between too little and too much retrieved context.',content:'<p>At query time, a system can represent the question and compare it with indexed information. The results can be ranked and a chosen number of candidates passed onward.</p><p><strong>Top-K</strong> is a retrieval setting, not a universal magic number. Too little context may miss information; too much may add noise, conflicting material, or consume context capacity.</p>',quiz:{question:'What does Top-K control in this simplified retrieval flow?',options:['How many top-ranked retrieval results are selected','How many tokens the LLM was trained on','How many times the model is retrained','How many databases must exist'],answer:0}},
  {id:'rag-06',title:'Grounding the LLM',description:'Inject retrieved context into a simulated model input, then remove it and compare the result.',difficulty:'Intermediate',xp:40,type:'rag-ground',objective:'Understand that retrieval only helps generation when relevant retrieved information is incorporated into model input.',content:'<p>Grounding here means using retrieved information as part of the input available to the generative model. Retrieval alone does not make an answer grounded.</p><p>The model still has to interpret the supplied context, and application design determines how missing, conflicting, or low-quality evidence is handled.</p>',quiz:{question:'What makes retrieval useful for generation?',options:['Relevant retrieved information is incorporated into the model input','The vector is shown to the user instead of the text','Retrieval automatically changes model weights','Any retrieved document guarantees a correct answer'],answer:0}},
  {id:'rag-07',title:'RAG Failure Modes',description:'Break a simulated RAG system by finding bad chunks, wrong retrieval, missing facts, stale sources, and conflicts.',difficulty:'Challenge',xp:50,type:'rag-failures',objective:'Recognize common retrieval and context-quality failures instead of treating RAG as magic.',content:'<p>RAG can fail before generation even starts. Poor chunking can split useful context, retrieval can select irrelevant material, the knowledge base can lack the requested fact, too much context can add noise, sources can become stale, and documents can disagree.</p><p>Handling these cases is application-level engineering. RAG can help ground responses, but it does not guarantee factual correctness.</p>',quiz:{question:'If retrieved sources disagree, what is a reasonable engineering response?',options:['Use source metadata/recency and application logic, or flag uncertainty','Blindly choose the first result','Pretend the conflict does not exist','Assume the newest-looking sentence is always correct'],answer:0}},
  {id:'rag-08',title:'RAG Architecture Builder',description:'Connect the major components into a coherent ingestion and query architecture.',difficulty:'Challenge',xp:60,type:'rag-builder',objective:'Assemble the core RAG architecture and understand what each connection represents.',content:'<p>Build two connected paths: an ingestion/indexing path and a query-time path. The user question should drive retrieval, and retrieved chunks should flow through a context builder before the LLM.</p><p>This is a conceptual builder; real systems may add parsing, filters, reranking, access control, evaluation, caching, or other components.</p>',quiz:{question:'Where should retrieved chunks go before generation in the basic architecture?',options:['Into a context-building/model-input step alongside the question','Directly into model weights','Only into the user interface','Back into the document parser'],answer:0}},
  {id:'rag-09',title:'Build a Mini RAG System',description:'Index a fictional AI handbook, ask a question, retrieve the best chunks, build context, generate a simulated answer, and inspect sources.',difficulty:'Challenge',xp:90,type:'mini-rag',objective:'Trace one complete RAG request from indexed knowledge to a sourced simulated answer.',content:'<p>You will operate a miniature local RAG system. It uses a fictional knowledge base, deterministic illustrative retrieval, a simulated context builder, and a simulated generator.</p><p>The goal is to see the complete loop: <strong>knowledge base → index → question → retrieval → context → generation → sources</strong>.</p>',quiz:{question:'Which stage happens after retrieval in the basic mini RAG flow?',options:['Build relevant context from the retrieved chunks','Retrain the embedding model','Delete the vector index','Turn embeddings into model weights'],answer:0}},
  {id:'rag-10',title:'RAG ARCHITECT — FINAL BOSS',description:'Design and evaluate a grounded documentation assistant from ingestion through retrieval, generation, sources, and missing-information handling.',difficulty:'Final Boss',xp:250,type:'rag-final',objective:'Design a coherent RAG architecture and justify decisions about retrieval, context, sources, and uncertainty.',content:'<p><strong>Scenario:</strong> A company wants employees to ask natural-language questions over internal documentation and receive answers based on that documentation.</p><p>Choose a coherent architecture, connect the query pipeline, decide how sources and missing information should be handled, then evaluate your design. Reasonable tradeoffs can receive credit.</p>',reasons:['Use chunks for focused retrieval where appropriate','Represent chunks with embeddings for semantic retrieval','Use retrieval to select relevant context','Pass the question and relevant context to the LLM','Keep source metadata visible for traceability','Handle missing information without pretending to know','Account for source freshness and conflicts'],
  }
];

export const phase7Achievements=[
 ['rag-rookie','📚','RAG ROOKIE','Complete Mission 1.'],['retrieval-thinker','🔀','RETRIEVAL THINKER','Complete Mission 2.'],['pipeline-mapper','🧩','PIPELINE MAPPER','Complete Mission 3.'],['knowledge-ingestor','📥','KNOWLEDGE INGESTOR','Complete Mission 4.'],['retrieval-specialist','🔎','RETRIEVAL SPECIALIST','Complete Mission 5.'],['grounding-guardian','🌱','GROUNDING GUARDIAN','Complete Mission 6.'],['rag-debugger','🐛','RAG DEBUGGER','Complete Mission 7.'],['rag-builder','🏗️','RAG BUILDER','Complete Mission 8.'],['mini-rag-engineer','🧠','MINI RAG ENGINEER','Complete Mission 9.'],['rag-architect','🏆','RAG ARCHITECT','Complete the Final Boss.']
].map(([id,icon,title,description])=>({id,icon,title,description}));

export const ragKnowledgeBase=[
 {id:'c1',title:'LLMs',source:'AI Learning Handbook',section:'LLMs',text:'Large language models generate text by predicting tokens from learned representations and the context supplied at request time.',tags:['llm','language','models']},
 {id:'c2',title:'Prompt Engineering',source:'AI Learning Handbook',section:'Prompt Engineering',text:'Prompt engineering shapes model input with clear instructions, context, examples, constraints, and desired output formats.',tags:['prompt','instructions','context']},
 {id:'c3',title:'Embeddings',source:'AI Learning Handbook',section:'Embeddings',text:'Embedding models produce numerical representations that encode useful learned patterns and can support similarity-based retrieval.',tags:['embeddings','vectors','similarity']},
 {id:'c4',title:'RAG Introduction',source:'AI Learning Handbook',section:'RAG',text:'Retrieval-augmented generation retrieves relevant external information and provides selected context to a generative model before producing an answer.',tags:['rag','retrieval','generation','context']},
 {id:'c5',title:'Retrieval Systems',source:'AI Learning Handbook',section:'RAG',text:'Retrieval systems can rank candidate chunks using semantic search, keyword search, hybrid strategies, metadata filters, or other application logic.',tags:['retrieval','search','ranking']},
 {id:'c6',title:'APIs',source:'AI Learning Handbook',section:'APIs',text:'An API lets software components communicate through a defined interface. LLM applications commonly use APIs to send requests and receive model responses.',tags:['api','applications','requests']},
 {id:'c7',title:'Local AI',source:'AI Learning Handbook',section:'Local AI',text:'Local AI runs model inference on hardware controlled by the application owner. Hardware, model size, runtime, memory, and performance are tradeoffs.',tags:['local','hardware','inference']},
 {id:'c8',title:'Agents',source:'AI Learning Handbook',section:'Agents',text:'Agentic systems can use models to choose actions and tools, observe results, and continue through multi-step tasks.',tags:['agents','tools','actions']},
 {id:'c9',title:'Evaluation',source:'AI Learning Handbook',section:'Evaluation',text:'AI applications need evaluation to measure retrieval quality, answer quality, failure cases, latency, and other task-specific outcomes.',tags:['evaluation','quality','testing']},
 {id:'c10',title:'Knowledge Freshness',source:'AI Learning Handbook',section:'RAG',text:'Retrieved knowledge is only as current as the indexed sources. Applications may need update workflows, metadata, timestamps, and source-quality checks.',tags:['rag','freshness','sources']}
];