import { curriculumLevels } from "./curriculum-registry.js";
import { evaluateLegacyAchievements } from "./achievements.js";

const STORAGE_KEY='ai-learn-player-state-v1';
const DAILY_XP_GOAL=100;
export const DEFAULT_STATE={xp:0,level:1,streak:0,lastActivityDate:null,dailyProgress:{date:null,xp:0,goalCompleted:false},completedLessons:[],achievements:[],unlockedLevels:[1],completedLevels:[],challengeScores:{}};
function localDateKey(date=new Date()){const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0'),d=String(date.getDate()).padStart(2,'0');return `${y}-${m}-${d}`}
function previousDateKey(dateKey){const [y,m,d]=dateKey.split('-').map(Number),date=new Date(y,m-1,d);date.setDate(date.getDate()-1);return localDateKey(date)}
function normalizeGamification(state){const today=localDateKey(),daily=state.dailyProgress&&typeof state.dailyProgress==='object'?state.dailyProgress:{};state.dailyProgress=daily.date===today?{date:today,xp:Math.max(0,Number(daily.xp)||0),goalCompleted:Boolean(daily.goalCompleted)}:{date:today,xp:0,goalCompleted:false};state.lastActivityDate=typeof state.lastActivityDate==='string'?state.lastActivityDate:null;state.streak=Math.max(0,Number(state.streak)||0);return state}
function applyLearningActivity(state,amount){normalizeGamification(state);const today=state.dailyProgress.date;state.dailyProgress.xp+=Math.max(0,Number(amount)||0);if(state.dailyProgress.xp>=DAILY_XP_GOAL)state.dailyProgress.goalCompleted=true;if(state.lastActivityDate!==today){if(!state.lastActivityDate)state.streak=state.streak>0?state.streak:1;else state.streak=state.lastActivityDate===previousDateKey(today)?state.streak+1:1;state.lastActivityDate=today}}
function applyMilestones(state){const count=state.completedLessons.length,checks=[['milestone-first-mission',count>=1],['milestone-ten-missions',count>=10],['milestone-fifty-missions',count>=50],['milestone-hundred-missions',count>=100],['milestone-1000-xp',state.xp>=1000],['milestone-5000-xp',state.xp>=5000],['milestone-7-day-streak',state.streak>=7],['milestone-30-day-streak',state.streak>=30]];const unlocked=[];checks.forEach(([id,ok])=>{if(ok&&!state.achievements.includes(id)){state.achievements.push(id);unlocked.push(id)}});return unlocked}
function reconcileProgression(state){curriculumLevels.forEach((level,index)=>{const lessons=level.lessons||[];if(!lessons.length||!lessons.every(lesson=>state.completedLessons.includes(lesson.id)))return;markLevelCompleted(state,level.id);if(index<curriculumLevels.length-1)unlockLevel(state,curriculumLevels[index+1].id);else unlockLevel(state,level.id+1)})}
export function loadState(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));if(!saved)return normalizeGamification({...DEFAULT_STATE});const state={...DEFAULT_STATE,...saved,completedLessons:Array.isArray(saved.completedLessons)?saved.completedLessons:[],achievements:Array.isArray(saved.achievements)?saved.achievements:[],unlockedLevels:Array.isArray(saved.unlockedLevels)?saved.unlockedLevels:[1],completedLevels:Array.isArray(saved.completedLevels)?saved.completedLevels:[],challengeScores:saved.challengeScores&&typeof saved.challengeScores==='object'?saved.challengeScores:{}};if(!state.unlockedLevels.includes(1))state.unlockedLevels.unshift(1);reconcileProgression(state);return normalizeGamification(state)}catch{return normalizeGamification({...DEFAULT_STATE})}}
export function saveState(state){let previous=null;try{previous=JSON.parse(localStorage.getItem(STORAGE_KEY))}catch{}const oldCompleted=Array.isArray(previous?.completedLessons)?previous.completedLessons:[];const newlyCompleted=state.completedLessons.filter(id=>!oldCompleted.includes(id));if(newlyCompleted.length){applyLearningActivity(state,Math.max(0,(Number(state.xp)||0)-(Number(previous?.xp)||0)));applyMilestones(state)}else normalizeGamification(state);localStorage.setItem(STORAGE_KEY,JSON.stringify(state));window.dispatchEvent(new CustomEvent('ailearn-gamification-updated',{detail:{newlyCompleted:newlyCompleted.length,rewardedXp:newlyCompleted.length?Math.max(0,(Number(state.xp)||0)-(Number(previous?.xp)||0)):0,level:state.level,streak:state.streak,dailyProgress:{...state.dailyProgress}}}))}
export function calculateLevel(xp){if(xp>=500)return 4;if(xp>=250)return 3;if(xp>=100)return 2;return 1}export function getLevelProgress(xp){const thresholds=[0,100,250,500],level=calculateLevel(xp);if(level===4)return{current:xp,total:xp||1,percent:100,max:true};const start=thresholds[level-1],end=thresholds[level];return{current:xp-start,total:end-start,percent:Math.min(100,((xp-start)/(end-start))*100),max:false}}export function addXP(state,amount){state.xp+=amount;state.level=calculateLevel(state.xp)}export function completeLesson(state,id,xp=25){if(state.completedLessons.includes(id))return false;state.completedLessons.push(id);addXP(state,xp);return true}export function isLevelUnlocked(state,id){return state.unlockedLevels.includes(id)||id===1}export function unlockLevel(state,id){if(!state.unlockedLevels.includes(id))state.unlockedLevels.push(id)}export function markLevelCompleted(state,id){if(!state.completedLevels.includes(id))state.completedLevels.push(id)}export function recordChallengeScore(state,id,score){state.challengeScores[id]=score}
export function unlockAchievements(state,lessons){return evaluateLegacyAchievements(state,lessons)}