import { evaluateLegacyAchievements } from "./achievements.js";

const STORAGE_KEY='ai-learn-player-state-v1';
const DAILY_XP_GOAL=100;
export const DEFAULT_STATE={xp:0,level:1,streak:0,lastActivityDate:null,dailyProgress:{date:null,xp:0,goalCompleted:false},completedLessons:[],achievements:[],unlockedLevels:[1],completedLevels:[],challengeScores:{}};
function localDateKey(date=new Date()){const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0'),d=String(date.getDate()).padStart(2,'0');return `${y}-${m}-${d}`}
function previousDateKey(dateKey){const [y,m,d]=dateKey.split('-').map(Number),date=new Date(y,m-1,d);date.setDate(date.getDate()-1);return localDateKey(date)}
function normalizeGamification(state){const today=localDateKey(),daily=state.dailyProgress&&typeof state.dailyProgress==='object'?state.dailyProgress:{};state.dailyProgress=daily.date===today?{date:today,xp:Math.max(0,Number(daily.xp)||0),goalCompleted:Boolean(daily.goalCompleted)}:{date:today,xp:0,goalCompleted:false};state.lastActivityDate=typeof state.lastActivityDate==='string'?state.lastActivityDate:null;state.streak=Math.max(0,Number(state.streak)||0);return state}
function applyLearningActivity(state,amount){normalizeGamification(state);const today=state.dailyProgress.date;state.dailyProgress.xp+=Math.max(0,Number(amount)||0);if(state.dailyProgress.xp>=DAILY_XP_GOAL)state.dailyProgress.goalCompleted=true;if(state.lastActivityDate!==today){if(!state.lastActivityDate)state.streak=state.streak>0?state.streak:1;else state.streak=state.lastActivityDate===previousDateKey(today)?state.streak+1:1;state.lastActivityDate=today}}
function applyMilestones(state){const count=state.completedLessons.length,checks=[['milestone-first-mission',count>=1],['milestone-ten-missions',count>=10],['milestone-fifty-missions',count>=50],['milestone-hundred-missions',count>=100],['milestone-1000-xp',state.xp>=1000],['milestone-5000-xp',state.xp>=5000],['milestone-7-day-streak',state.streak>=7],['milestone-30-day-streak',state.streak>=30]];const unlocked=[];checks.forEach(([id,ok])=>{if(ok&&!state.achievements.includes(id)){state.achievements.push(id);unlocked.push(id)}});return unlocked}
const LEVEL_REQUIREMENTS=[['ai','genai','llm','apps','usecases'],['llm-01','llm-02','llm-03','llm-04','llm-05','llm-06','llm-07','llm-08','llm-final'],['prompt-01','prompt-02','prompt-03','prompt-04','prompt-05','prompt-06','prompt-07','prompt-08','prompt-09','prompt-10'],['app-01','app-02','app-03','app-04','app-05','app-06','app-07','app-08','app-09','app-10'],['local-01','local-02','local-03','local-04','local-05','local-06','local-07','local-08','local-09','local-10'],['embed-01','embed-02','embed-03','embed-04','embed-05','embed-06','embed-07','embed-08','embed-09','embed-10'],['rag-01','rag-02','rag-03','rag-04','rag-05','rag-06','rag-07','rag-08','rag-09','rag-10'],['agent-01','agent-02','agent-03','agent-04','agent-05','agent-06','agent-07','agent-08','agent-09','agent-10'],['agent9-01','agent9-02','agent9-03','agent9-04','agent9-05','agent9-06','agent9-07','agent9-08','agent9-09','agent9-10'],['mcp-01','mcp-02','mcp-03','mcp-04','mcp-05','mcp-06','mcp-07','mcp-08','mcp-09','mcp-10'],['orch-01','orch-02','orch-03','orch-04','orch-05','orch-06','orch-07','orch-08','orch-09','orch-10'],['agentic-01','agentic-02','agentic-03','agentic-04','agentic-05','agentic-06','agentic-07','agentic-08','agentic-09','agentic-10']];
function reconcileProgression(state){LEVEL_REQUIREMENTS.forEach((ids,index)=>{if(ids.every((id)=>state.completedLessons.includes(id))){if(index<LEVEL_REQUIREMENTS.length)unlockLevel(state,index+2);markLevelCompleted(state,index+1)}})}
export function loadState(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));if(!saved)return normalizeGamification({...DEFAULT_STATE});const state={...DEFAULT_STATE,...saved,completedLessons:Array.isArray(saved.completedLessons)?saved.completedLessons:[],achievements:Array.isArray(saved.achievements)?saved.achievements:[],unlockedLevels:Array.isArray(saved.unlockedLevels)?saved.unlockedLevels:[1],completedLevels:Array.isArray(saved.completedLevels)?saved.completedLevels:[],challengeScores:saved.challengeScores&&typeof saved.challengeScores==='object'?saved.challengeScores:{}};if(!state.unlockedLevels.includes(1))state.unlockedLevels.unshift(1);reconcileProgression(state);return normalizeGamification(state)}catch{return normalizeGamification({...DEFAULT_STATE})}}
export function saveState(state){let previous=null;try{previous=JSON.parse(localStorage.getItem(STORAGE_KEY))}catch{}const oldCompleted=Array.isArray(previous?.completedLessons)?previous.completedLessons:[];const newlyCompleted=state.completedLessons.filter(id=>!oldCompleted.includes(id));if(newlyCompleted.length){applyLearningActivity(state,Math.max(0,(Number(state.xp)||0)-(Number(previous?.xp)||0)));applyMilestones(state)}else normalizeGamification(state);localStorage.setItem(STORAGE_KEY,JSON.stringify(state));window.dispatchEvent(new CustomEvent('ailearn-gamification-updated',{detail:{newlyCompleted:newlyCompleted.length,rewardedXp:newlyCompleted.length?Math.max(0,(Number(state.xp)||0)-(Number(previous?.xp)||0)):0,level:state.level,streak:state.streak,dailyProgress:{...state.dailyProgress}}}))}
export function calculateLevel(xp){if(xp>=500)return 4;if(xp>=250)return 3;if(xp>=100)return 2;return 1}export function getLevelProgress(xp){const thresholds=[0,100,250,500],level=calculateLevel(xp);if(level===4)return{current:xp,total:xp||1,percent:100,max:true};const start=thresholds[level-1],end=thresholds[level];return{current:xp-start,total:end-start,percent:Math.min(100,((xp-start)/(end-start))*100),max:false}}export function addXP(state,amount){state.xp+=amount;state.level=calculateLevel(state.xp)}export function completeLesson(state,id,xp=25){if(state.completedLessons.includes(id))return false;state.completedLessons.push(id);addXP(state,xp);return true}export function isLevelUnlocked(state,id){return state.unlockedLevels.includes(id)||id===1}export function unlockLevel(state,id){if(!state.unlockedLevels.includes(id))state.unlockedLevels.push(id)}export function markLevelCompleted(state,id){if(!state.completedLevels.includes(id))state.completedLevels.push(id)}export function recordChallengeScore(state,id,score){state.challengeScores[id]=score}
export function unlockAchievements(state,lessons){return evaluateLegacyAchievements(state,lessons)}